### ISSUE TITLE
Demo: Data Vault + Compliance App

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PyGrid#213]
The goal of this application is to allow one person (a Data Owner) to spin up a grid node, load it with data, and allow another (or several) people to use it to train models. 

Most importantly, the purpose of this app is to create a "request queue" so that when a data scientist calls .get() on a tensor, the Data Owner can log into a web UI (hosted by their grid node) and Approve/Deny the .get() requests.

The most important feature is that we empower the Data Owner to have all the information they need to be able to responsibly make .get() requests.

**Comment by IonesioJunior** [comment]
I'm on it.

**Comment by hericlesme** [comment]
@IonesioJunior do you need help with the UI? :nerd_face:

**Comment by IonesioJunior** [comment]
@hericlesme 
Yeah, of course! I'd love to get some help. :)

**Comment by iamtrask** [comment]
In thinking about this, there are a few things that will be very useful for a compliance officer to use for making decisions on when to allow / deny .get() requests:

- visually looking at the tensor being requested
- reading a description of why the data scientist wants to see it (we should extend .get() with an optional "reason" string parameter)
- the shape of the tensor
- the privacy budget of the tensor (epsilon)
- the list of operations used to create the final result.
- a pseudo-source code generated from the operations
- a graph view of the operations
