### ISSUE TITLE
Automatic Differential Privacy

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PyGrid#228]
Part of #223 Project
--

**Description:** In this epic, we want to add functionality to Grid and PySyft which allows for the automatic tracking of a privacy budget for entities in a dataset over time such that we can make formal guarantees around the amount of information leaked whenever a private asset is published (such as an AI model). It is preferred for this infrastructure to be as automated as possible, but applications (UIs) which allow for the vetting of digital assets for private information by humans are also allowed (and are likely essential for earlier adopters).

**Comment by pengyuan-zhou** [comment]
> ## Part of #223 Project
> **Description:** In this epic, we want to add functionality to Grid and PySyft which allows for the automatic tracking of a privacy budget for entities in a dataset over time such that we can make formal guarantees around the amount of information leaked whenever a private asset is published (such as an AI model). It is preferred for this infrastructure to be as automated as possible, but applications (UIs) which allow for the vetting of digital assets for private information by humans are also allowed (and are likely essential for earlier adopters).

Hi, has this been implemented?
