### ISSUE TITLE
Global IDs for public workers

### ISSUE THREAD

**Issue by jlebensold** [OpenMined/PyGrid#236]
Currently the client of a grid worker provides a worker ID and it seems we should have some sort of unique token for session management, assuming that we would want to have multiple workers on the same grid

**Comment by mari-linhares** [comment]
Related to #200

**Comment by mari-linhares** [comment]
Do you think this is still relevant @IonesioJunior ?

**Comment by IonesioJunior** [comment]
Currently, the grid gateway component already controls the use of global id's by mapping registered nodes ( { node_id : node_address } ).

**Comment by IonesioJunior** [comment]
Now, nodes send their own node ids to the client after setting the connection and perform the authentication process. Each registered user has a specific node worker/id.
Fixed #342
