### ISSUE TITLE
Grid search fails if multiple tensors are in the same node

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/PyGrid#284]
If a single node holds 2 or more tensors with the same tag grid search returns only one pointer.

**Comment by DanyEle** [comment]
I'm getting an error saying that the object with the tag could not be decoded even if there is just one single object:

![image](https://user-images.githubusercontent.com/4907418/64844717-c550cc80-d608-11e9-95be-98911021d4a7.png)
