### ISSUE TITLE
Error while building Docker image requirements for app/websocket

### ISSUE THREAD

**Issue by DanyEle** [OpenMined/PyGrid#299]
When running the following command:

`sudo docker build -t node ./app/websocket/ `

I get this error:

![error_grid](https://user-images.githubusercontent.com/4907418/64728193-bec43700-d4da-11e9-81ad-c0114cc70bda.png)

In phase (6), when installing requirements.

However, when running 

`pip3 install -r app/websocket/requirements.txt`

I do not get any issues.

I tried to look online for different solutions related to installing the psycopg2 library manually from source and from the package manager, but none of them worked. The issue just occurs when installing the docker image.

**OS:** Ubuntu 18.04 LTS

**Comment by IonesioJunior** [comment]
Fixed #301
