### ISSUE TITLE
Installation feedback on Mac

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PyGrid#306]
I did the 3 installations procedures mentioned in the README.md, it takes a *long* time, I didn't found any element to know if all 3 are needed!

**Grid library**
> `python setup.py install`

`error: Could not find suitable distribution for Requirement.parse('flask_migrate')`

I had to call `pip install Flask-Migrate`

**Grid Node** 
> `pip install -r requirements.txt`

We are installing torch 1.2.0, do we support it?
`Collecting torch (from -r requirements.txt (line 18))
  Downloading https://files.pythonhosted.org/packages/ba/88/7640344d841e97b9a1531385caac39d984b2c6f4abd1376e1ce0de3a0933/torch-1.2.0-cp37-none-macosx_10_7_x86_64.whl (59.9MB)`
Because I have this error happening next:
```
ERROR: syft 0.1.27a1 has requirement torch==1.1, but you'll have torch 1.2.0 which is incompatible.
ERROR: syft 0.1.27a1 has requirement torchvision==0.3.0, but you'll have torchvision 0.4.0 which is incompatible.
```

**Error with psycopg2** (related to having Mac)
```
...
... lpq -lssl -lcrypto -o build/lib.macosx-10.9-x86_64-3.7/psycopg2/_psycopg.cpython-37m-darwin.so
    ld: library not found for -lssl
```
Solution
```
brew install openssl
env LDFLAGS="-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib" pip --no-cache install psycopg2
```

**Install jupyter** and launch:
`Error loading server extension jupyter_http_over_ws`
Solution:
`pip install jupyter_http_over_ws`

In the notebooks, I have Warnings from tensorflow 1.14:
```
site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
...
```

**Comment by Quisher** [comment]
which branch did you use.. Cause as per https://github.com/OpenMined/Grid/blob/dev/requirements.txt

I think the only version of torch that will be installed is that which comes while installing syft.

**Comment by mari-linhares** [comment]
Maybe have a section for mac installation on the README.md?

**Comment by Quisher** [comment]
I can take this up. Just need more info from @LaRiffle

**Comment by LaRiffle** [comment]
I took the first one that came when you clone the repo, i think it's dev

**Comment by Quisher** [comment]
created a new clean env, using Conda and python 3.6
- Torch version issue. (not happening on latest dev branch)
- didn't have to install flask-migrate
- Jupyter launching perfectly fine (used `pip install jupyterlab`) - we can add a command for installing Jupiter, in readme.md so everyone does it in a specified way.
- psycog2 issue with ssl - won't occur for users with Xcode command line tools or open ssl already installed. We can create a common issues section and add this well known issue and how to mitigate it there.
