### ISSUE TITLE
When a worker's database raises an error we should restart the session

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/PyGrid#318]
An example is when a user tries to serve 2 models with the same id. We correctly don't let the user doing this but the database session is broken.

**Comment by iamtrask** [comment]
or we should try/catch the error and just return that?

**Comment by Quisher** [comment]
> or we should try/catch the error and just return a message about the error?

we are already doing that returning the errors to grid client as they are.

The session broken error happens when add to db commit fails.
Solution is to do a rollback for such commits.
