### ISSUE TITLE
Name Change: Grid -> PyGrid

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PyGrid#321]
Thoughts? Seems like this is a better name given that there's a good chance we'll have multiple grid libs.

**Comment by Quisher** [comment]
I always wondered why it isn't pygrid or opengrid in the first place.

**Comment by cereallarceny** [comment]
As one of the authors of grid.js - I'd love to see this.  😉

**Comment by DanyEle** [comment]
I definitely support it!

**Comment by mari-linhares** [comment]
I support this game change, but I don't think this should be done before October. We have a lot of links (some important ones) that will break if we rename the repo.

**Comment by cereallarceny** [comment]
@mari-linhares which links are you referring to specifically?  If you're worried about people's git links being broken, Github automatically forwards traffic from the old URL: https://help.github.com/en/articles/renaming-a-repository

**Comment by iamtrask** [comment]
Given @cereallarceny 's input to Marianne's concerns, I have updated the name.
