### ISSUE TITLE
Add grid logo to Readme

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PyGrid#327]
Logos can be found here https://github.com/OpenMined/design-assets/tree/master/logos/PyGrid

**Comment by jess-s** [comment]
I can take this one.  Do we need to be assigned the issues we want to work on?

**Comment by IonesioJunior** [comment]
Ohh, I'm sorry @jess-s, I had not seen your message before.
But feel free to take another one, your help will be very welcome :heart:!
If you need some help, you can find me on slack :)

**Comment by IonesioJunior** [comment]
Fixed #329
