### ISSUE TITLE
Error using Docker-compose

### ISSUE THREAD

**Issue by fbalicchia** [OpenMined/PyGrid#339]
Hey, first off all thanks for interesting project and I'm newbie with PyGrid and trying to build 
docker image and use docker-compose but I'm experiencing in some errors.
Align env variable to actual code base docker-compose works for me

Please review PR 
thanks

--Filippo

**Comment by IonesioJunior** [comment]
Hello @fbalicchia !
I believe you're working on it (#340 ).
Could I assign this task to you?

**Comment by IonesioJunior** [comment]
Solved! #344

**Comment by fbalicchia** [comment]
Hi @IonesioJunior yes I can work on but if you have urgency, please feel free to do it, At moment of write I work on it in my spare time

**Comment by IonesioJunior** [comment]
No problem @fbalicchia , It's just to keep the repository updated.
You're doing a great job! :)

**Comment by IonesioJunior** [comment]
Fixed! #340
