### ISSUE TITLE
Error while building Docker image requirements for gateway

### ISSUE THREAD

**Issue by hericlesme** [OpenMined/PyGrid#343]
An error similar to that reported in issue #299 is happening when running the command:
- `docker build -t gateway ./gateway .` 

In Step 6/10: 
- `RUN pip3 install -r requirements.txt`

The error happens during `psycopg2` library installation

**OS:** Ubuntu 18.04 LTS

**Comment by hericlesme** [comment]
It looks like replacing `psycopg2` with `psycopg2-binary`  in the app/websocket/requirements.txt file seems to fix it.

_Originally posted by @DanyEle in https://github.com/OpenMined/PyGrid/issues/299#issuecomment-530804906_

**Comment by IonesioJunior** [comment]
Hello @hericlesme!
Are you working on it?
 Could I assign this task to you?

**Comment by hericlesme** [comment]
Yes @IonesioJunior!
