### ISSUE TITLE
Add documentation build to CI verification

### ISSUE THREAD

**Issue by Benardi** [OpenMined/PyGrid#352]
**Is your feature request related to a problem? Please describe.**
I believe it would be helpful to have the Continuous Integration check whether a given PR has damaged the documentation build. 
This way it would be ensured that the documentation is available at any given time. 

**Describe the solution you'd like**
A 'patch' to the existing Continuous Integration via Travis to add a check for the documentation build.

**Describe alternatives you've considered**
Employing **tox** to explicitly declare a testing environment **docs** and integrate it to the Travis verification routine.
* https://github.com/numpy/numpy/blob/master/tox.ini (Uses tox)
* https://github.com/tox-dev/tox/blob/master/tox.ini (Has a docs environment)

Technologies:
* Travis, sphinx, Makefile
         + Optionally: Tox

**Comment by IonesioJunior** [comment]
This is a great issue to improve code quality!

**Comment by Benardi** [comment]
I would like to work on this

**Comment by IonesioJunior** [comment]
Perfect!  Thank you @Benardi! :rocket:
