### ISSUE TITLE
Relay setup.py logic to a setup.cfg

### ISSUE THREAD

**Issue by Benardi** [OpenMined/PyGrid#356]
**Is your feature request related to a problem? Please describe.**
It's often hard to read a `setup.py` when a project grows enough. Relaying the logic to a `setup.cfg` could make it easier for someone (especially someone new to the project) to get acquainted with the module's configuration.

**Describe the solution you'd like**
Create a `setup.cfg` that would encapsulate part of the logic of the `setup.py`

**Describe alternatives you've considered**
* EMploy the package Python Build Reasonableness (pbr) to ease the transition.

**Additional context**
* https://github.com/OpenMined/PySyft/blob/dev/setup.cfg
* https://github.com/django/django/blob/master/setup.cfg

**Comment by Benardi** [comment]
I'd like to work on this

**Comment by IonesioJunior** [comment]
Ok! You're doing a great job @Benardi!

**Comment by Benardi** [comment]
Thanks, mate! Glad to be of help.
