### ISSUE TITLE
[Notebook] Federated SMS Spam Prediction

### ISSUE THREAD

**Issue by IonesioJunior** [OpenMined/PyGrid#371]
Reproduce [Federated SMS Spam Prediction](https://github.com/OpenMined/PySyft/tree/master/examples/tutorials/advanced/Federated%20SMS%20Spam%20prediction) using PyGrid Network.

**Acceptance criteria:**
- Keep the same structure used at [Federated SMS Spam Prediction](https://github.com/OpenMined/PySyft/tree/master/examples/tutorials/advanced/Federated%20SMS%20Spam%20prediction).
- Keep the author's name and add your name.
- Create a notebook to register dataset tensors with tags.
- Create a different notebook using PyGrid network to search datasets by tags.
- Perform Federated training using the found pointers.

**Comment by murarugeorgec** [comment]
Could I work on this one? Or if there is an important feature/bug I would happily work on it.

**Comment by IonesioJunior** [comment]
Yeah! For sure!
