### ISSUE TITLE
[Notebook] Federated Word Vectors

### ISSUE THREAD

**Issue by IonesioJunior** [OpenMined/PyGrid#372]
Reproduce [Federated Word Vectors](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/advanced/Federated%20Word%20Vectors.ipynb) using PyGrid Architecture.

**Acceptance criteria:**
- Keep the same structure used at [Federated Word Vectors](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/advanced/Federated%20Word%20Vectors.ipynb).
- Keep the author's name and add your name.
- Create a notebook to register dataset tensors with tags.
- Create a different notebook using PyGrid network to search datasets by tags.
- Perform Federated training using the found pointers.

**Comment by allibell** [comment]
I'd like to work on this!

**Comment by IonesioJunior** [comment]
Yeah, for sure! :rocket:

**Comment by IonesioJunior** [comment]
Hello @allibell! Are you still interested in this issue? :)

**Comment by debajit15kgp** [comment]
Hello 
I would love to work on this. I hope this issue is still open?

**Comment by IonesioJunior** [comment]
Hello @debajit15kgp! Yeah, for sure! :)

**Comment by ratmcu** [comment]
@IonesioJunior is this issue still open? Can I work with @debajit15kgp to create the notebooks?

**Comment by Akramz** [comment]
@ratmcu are you actively working on this? I'm also interested in contributing to the notebooks.

**Comment by ratmcu** [comment]
@Akramz I am not,
