### ISSUE TITLE
[Notebook] Encrypted Linear Regression

### ISSUE THREAD

**Issue by IonesioJunior** [OpenMined/PyGrid#373]
Reproduce [Encrypted Linear Regression](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/advanced/Encrypted%20Linear%20Regression.ipynb) notebook.

**Acceptance criteria:**
- Keep the author's name and add your name.
- Perform Encrypted Linear Regression using PyGrid Nodes.

**Comment by Benardi** [comment]
I would like to work on this

**Comment by IonesioJunior** [comment]
It's yours @Benardi!
