### ISSUE TITLE
Update the websocket API

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PyGrid#393]
**Describe the bug**
The websocket API is outdated.

**Expected behavior**
The ```grid_node_websocket_api.rst``` should contain the correct functions.

**Comment by gmuraru** [comment]
@IonesioJunior Made a PR with the documentation update, but I see there are no tests for the websocket REST API. Should I include some tests in this issue or should I create a separate one?

**Comment by IonesioJunior** [comment]
Yes, please!
