### ISSUE TITLE
Decode 'utf-8' error when serve_model is called

### ISSUE THREAD

**Issue by joaolcaas** [OpenMined/PyGrid#402]
**Describe the bug**
The bug occuors when i try to host a big model (AlexNet in this case) on a worker. A byte (0xc9 in specific) can not be decoded by utf-8. The code just broke and the model is not hosted.

**To Reproduce**
1. Start workers and grid
2. Try to host a big model calling `worker.serve_model`. In this case, i used AlexNet from torch.models, wich you can find [here](https://github.com/pytorch/vision/blob/master/torchvision/models/alexnet.py).

3. Now, the following error appears: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 8: invalid continuation byte

**Expected behavior**
The code broke and the model is not hosted

**Screenshots**
![error](https://user-images.githubusercontent.com/23393117/69571519-fb171780-0fa0-11ea-903a-956541e308d9.png)

**Desktop (please complete the following information):**
 - OS: MATE
 - Version 1.12.1

**Additional context**
I just opened an PR #400 and tried to fix it adding a try except block to decode the 0xc9 byte. Locally in my machine, using just 'latin-1' it was fixed, but i think that's not the best solution. Appreciate it.

**Comment by IonesioJunior** [comment]
Hello @joaolcaas!
Thank you for reporting this bug. I'll take a look a soon as possible.

**Comment by IonesioJunior** [comment]
Fixed #400
