### ISSUE TITLE
Create PyGrid ANSIBLE playbook 

### ISSUE THREAD

**Issue by IonesioJunior** [OpenMined/PyGrid#407]
**Is your feature request related to a problem? Please describe.**
We want to create an easy way to deploy our platform on cloud providers.

**Describe the solution you'd like**
Create PyGrid **ANSIBLE playbook** to automatic deployment on cloud platforms ( AWS / GCP )

**Comment by sfmajors373** [comment]
May I try this one?

**Comment by IonesioJunior** [comment]
Hello @sfmajors373!
It's yours! :)

**Comment by IonesioJunior** [comment]
Hello @sfmajors373! Are you still interested in this task? :)

**Comment by javanlacerda** [comment]
May I do it?

**Comment by IonesioJunior** [comment]
@javanlacerda It's yours!

**Comment by hericlesme** [comment]
Closed by #472
