### ISSUE TITLE
Create Kubernetes config file

### ISSUE THREAD

**Issue by IonesioJunior** [OpenMined/PyGrid#408]
**Is your feature request related to a problem? Please describe.**
We want to provide container orchestration to automate the deployment, sizing, and management to PyGrid node containers.

**Describe the solution you'd like**
We want to provide scaling up/down, health check and fault tolerance to our platform using Kubernetes.

**Comment by gantir** [comment]
@IonesioJunior, can I work on this issue. I already have started looking into this.

**Comment by IonesioJunior** [comment]
It's yours! :)
