### ISSUE TITLE
Add support for scopes

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGrid#411]
**Is your feature request related to a problem? Please describe.**
We must allow syft.js to connect to PyGrid. In order to do so, we need to have some concept of a "scope".

**Describe the solution you'd like**
Scope, as it pertains to grid.js (the only socket library syft.js currently works with), is simply a private "room" where multiple workers can train and predict together. A worker should only ever be a part of 1 scope at a time. Likewise, a scope can include one or many users. This will be mandatory for [implementing WebRTC](https://github.com/OpenMined/PyGrid/issues/412) and eventually [adding plan and protocol support to PyGrid](https://github.com/OpenMined/PyGrid/issues/413).

**Additional context**
[Here is some required reading for fully understanding the requirements of this ticket.](https://github.com/OpenMined/grid.js/blob/seeding/SOCKETS.md)

In particular, please read the `get-protocol` section.

**Comment by hericlesme** [comment]
@cereallarceny I'll be working on it. :nerd_face:

**Comment by IonesioJunior** [comment]
It's yours! :)
