### ISSUE TITLE
Add support for WebRTC

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGrid#412]
**Is your feature request related to a problem? Please describe.**
We must allow syft.js and other worker libraries to connect via the WebRTC protocol.

This issue is blocked by:
- https://github.com/OpenMined/PyGrid/issues/411

**Describe the solution you'd like**
To allow for the direct, peer-to-peer connection of workers, we need PyGrid to act as a [signaling server in the WebRTC workflow](https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/). The good news is that [this code is 100% feature-complete in grid.js](https://github.com/OpenMined/grid.js/blob/seeding/src/socket.js#L132) and may (more or less) be copied and changed from Javascript to Python.

**Additional context**
[Here is some required reading for fully understanding the requirements of this ticket.](https://github.com/OpenMined/grid.js/blob/seeding/SOCKETS.md)

In particular, please read the sections titled `webrtc: join-room`, `webrtc: internal-message`, and `webrtc: peer-left`. The API in PyGrid must follow the API in grid.js 100%.

**Comment by hericlesme** [comment]
Closed by #447
