### ISSUE TITLE
Automated docker builds 

### ISSUE THREAD

**Issue by hericlesme** [OpenMined/PyGrid#417]
**Is your feature request related to a problem? Please describe.**
The docker images of PyGrid nodes and Gateway are built locally only. Having images in remote repositories (such as Docker Hub, or GitHub Package) can be helpful. The image could just be pulled, either using Docker locally or for example in a Kubernetes deployment.

**Describe the solution you'd like**
PyGrid could have automated builds that automatically push images to remote repositories.

**Additional context**
#415

**Comment by gantir** [comment]
@hericlesme would you have the credentials for either of dockerhub or GitHub packages. Else can push to mine

I can fix this along with #415.

**Comment by hericlesme** [comment]
The PyGrid images on the Docker hub are still not being updated automatically. Now that we are using **GitHub Actions**, the appropriate thing would be to create a step that updates the image whenever there is a push in the `dev` branch.
