### ISSUE TITLE
Grid Node Status is offline

### ISSUE THREAD

**Issue by Bingyy** [OpenMined/PyGrid#418]
I setup a node in macos, but the node status is offline, and when i send tensor to it, such as x tensor, but worker._objects shows `{}`, is it because of status offline?

**Comment by tallalj** [comment]
where are you seeing the offline status? can you elaborate

**Comment by matthiaslau** [comment]
@Bingyy with offline status do you mean what is shown on the dashboard when you open the worker URL in a browser? (when looking at the code this should always be offline as it uses the /identity enpoint which was removed here: https://github.com/OpenMined/PyGrid/commit/9b3371841c9c5308260add5f37b82f7d598dadf7)

So this has nothing to do with tensors not being sent to a worker. Could you please post your code?

**Comment by hericlesme** [comment]
Fixed by #443
