### ISSUE TITLE
Add "host_federated_training" method to PyGrid

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGrid#435]
**Note: Please consult [issue 2995 on PySyft](https://github.com/OpenMined/PySyft/issues/2995) for beginning on this one.**

This will allow for training cycles to begin on end-user devices. The developer needs to connect to an existing PyGrid gateway and send the model, worker plans, worker protocols, averaging plan, and various configurations to be stored in PyGrid properly.

Here's a look at what this might look like:

```py
import grid as gr

pygrid = gr.WebsocketGridClient(
  hook,
  id="my-name",
  address="https://localhost:3000"
)

pygrid.connect()

pygrid.host_federated_training(
  model=model,
  client_plans={ "training_plan": training_plan },
  client_protocols={ "secure_agg_protocol": secure_aggregation_protocol },
  client_config=client_config,
  server_averaging_plan=averaging_plan,
  server_config=server_config
)
```

Note that this means that PyGrid will need to now be able to host:
- Models
- Plans
- Protocols (refactor pending)
- Various configurations (one for the client and another for the PyGrid server)

**Comment by IonesioJunior** [comment]
This issue was finished on the PyGrid side. Should we create a new one on the client side (PySyft)?

**Comment by cereallarceny** [comment]
As in, completely finished?  We need to have the method available when communicating with PyGrid. Is that what you mean by creating the issue in PySyft? If so, go ahead.

**Comment by hericlesme** [comment]
@cereallarceny Yes. The grid library no longer exists here, it is now a [PySyft module](https://github.com/OpenMined/PySyft/tree/master/syft/grid). So the interface you used in the example is no longer available. I propose the creation of a client in this PySyft module. We would have the necessary methods, and these would use the endpoints that we implemented on the PyGrid side.

**Comment by hericlesme** [comment]
So, the work on the PyGrid part, as @IonesioJunior said, is ready. So, yes, the next steps are to create issues in PySyft and finish the job there. :rocket:

**Comment by cereallarceny** [comment]
Go ahead and do that, shoot me the issue link when you create it!  :)

**Comment by hericlesme** [comment]
@cereallarceny https://github.com/OpenMined/PySyft/issues/3153

**Comment by cereallarceny** [comment]
Closed by https://github.com/OpenMined/PySyft/pull/3252
