### ISSUE TITLE
Add "get_model" method to PyGrid

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGrid#436]
Assuming we’ve finished all the cycles in the federated learning process, the model will now be ready for inspection by the developer and may be used for inference, retrained, or whatever they desire. The developer may decide to pull a specific version of a model, or may optionally decide to even pull a specific checkpoint instead. The process of federated learning is now considered complete. This may look something like the following:

```py
import grid as gr

pygrid = gr.WebsocketGridClient(
  hook,
  id="my-name",
  address="https://localhost:3000"
)

pygrid.connect()

trained_fl_model = pygrid.get_model(name="my-federated-model", version="0.1.0", checkpoint="latest")
```

**Comment by IonesioJunior** [comment]
Once the endpoint has been built, I think it's valid to close this issue and track the progress of the `client-side` development in the PySyft repository.

**Comment by cereallarceny** [comment]
Sure thing. Do we have an issue for this on PySyft?
