### ISSUE TITLE
Add a few predefined averaging plans (like “Federated Average”) to PyGrid

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGrid#440]
According to https://github.com/OpenMined/PyGrid/issues/439, we will have averaging plans that a model developer will need to upload in order to average the model.

However, many of these averaging models are quite similar, and a few are commonly used by most developers. One such averaging algorithm would be a plan-based implementation of Google's "Federated Averaging" which was detailed in their two opening papers related to federated learning.

As per this ticket, we want to include a few "pre-coded" averaging algorithms that you can choose by name. The first one we'll implement will be `"FEDERATED_AVERAGE"`, followed by other common model averaging algorithms. When calling `test_federated_training()` or `host_federated_training()`, one could optionally specify a string with the name of the commonly-used algorithm in place of specifying a specific plan.

**Comment by cereallarceny** [comment]
@IonesioJunior This auto closing of issues kind of interferes with my team’s roadmap. Can we please turn this off? Or perhaps only have it apply for issues that don’t have certain labels (epic, etc)?

**Comment by joaolcaas** [comment]
hey guys, this issue still relevant? I'm trying to figure it out the better place to put this predefined plans

**Comment by cereallarceny** [comment]
It is @joaolcaas - please leave it here for now. I'll assign it to a member of my team in the next week or two.

**Comment by joaolcaas** [comment]
Sure, @cereallarceny

**Comment by madhavajay** [comment]
Complete
