### ISSUE TITLE
docker-compose doesn't start the grid-nodes 

### ISSUE THREAD

**Issue by sgaseretto** [OpenMined/PyGrid#459]
I downloaded the docker-compose.yml file and tried to launch it, but I'm getting an error related to the Database. I don't know if I have to start an sqlite database somewhere before running docker-compose and use volumes to move the database from my file system to the docker container, running something inside the gateway and then rerun ```docker-compose up``` or what. The README does not specify any additional steps besides executing the ```docker-compose up``` command

**Comment by hericlesme** [comment]
@sgaseretto can you please confirm if is this the error?
> RuntimeError: Invalid database address : Set DATABASE_URL environment var or add test_config parameter at create_app method.

And you’re using our docker hub images, right?

**Comment by sgaseretto** [comment]
Hello @hericlesme! Yes, that's the error I'm getting and I'm using the DockerHub Images

**Comment by hericlesme** [comment]
@sgaseretto I noticed that there is a problem with the auto-update of the Docker hub images, they are out of date (_last update 2 months ago_). If you try to build your own images, it will probably work. And I'll work to keep the PyGrid images updated. Thank you for reporting this issue! :rocket: :heart:

**Comment by sgaseretto** [comment]
Yes, now that I builded my own images, it worked! Thanks for your response @hericlesme

**Comment by hericlesme** [comment]
Great, @sgaseretto! :smile:

**Comment by hericlesme** [comment]
The docker compose is now starting the nodes correctly. To make sure it doesn't happen again, we'll work on #417. Thank you @sgaseretto!

**Comment by urwithajit9** [comment]
Today, i got the same error after pulling image from docker-hub and running $docker run openmined/grid-gateway.
What are the possible solutions? I am new to docker so not comfortable with build my own
