### ISSUE TITLE
Docker host networking works only for Linux

### ISSUE THREAD

**Issue by youben11** [OpenMined/PyGrid#460]
## Problem

The Docker host networking driver only works on Linux hosts, this makes deployments of the grid hard for mac and windows users, they will need to update the docker-compose.yml file.

## Solution

We can bind ports to localhost (e.g. binding port of the grid gateway to localhost:5000) and this will make the docker-compose file usable in most platforms.

**Comment by IonesioJunior** [comment]
Solved, thank you @youben11!
