### ISSUE TITLE
FL Worker Cycle Request

### ISSUE THREAD

**Issue by IonesioJunior** [OpenMined/PyGrid#464]
## FL Worker Cycle Request

**HTTP endpoint**: `POST /federated/cycle-request`
**Socket type**: `federated/cycle-request`

**Request data**:
```json
{
  "worker_id": "ID OF THE WORKER",
  "model": "my-federated-model",
  "version": "0.1.0",
  "ping": "8ms",
  "download": "46.3mbps",
  "upload": "23.7mbps"
}
```
_Note that `version` supplied above is an optional argument._

This endpoint is where the worker library (syft.js, KotlinSyft, or SwiftSyft) is attempting to join an active federated learning cycle. PyGrid, depending on the current state of the cycle, the speed of the worker's connection, and how many workers have already been chosen.

Given this information, PyGrid will send **one of two responses**:

**Rejection**
```json
{
  "status": "rejected",
  "timeout": 2700
}
```

This means that the worker was rejected from the current cycle and asked to request to join another cycle in 2700 seconds. The number of seconds will depend on when the next cycle is expected to start.

**Accepted**
```json
{
  "status": "accepted",
  "request_key": "LONG HASH VALUE",
  "plans": { "training_plan": "ID OF THE TRAINING PLAN", "another_plan": "ID OF ANOTHER PLAN" },
  "client_config": "CLIENT CONFIG OBJECT",
  "protocols": { "secure_agg_protocol": "ID OF THE PROTOCOL" },
  "model": "ID OF THE MODEL"
}
```

In the event that the worker is accepted into the current cycle, they will be sent a named list of the ID's of various plans they need to execute, a named list of the ID's of various protocols they need to execute, the id of the model, and the client config. The plans, protocols, and model will not be downloaded in this response. Instead, the worker will need to make an additional request to receive them (due to the size constraints of the response). They will pass the `request_key` given above as a form of "authenticating" the download request. This is specific to the relationship between the worker AND the cycle and cannot be reused for future cycles or other workers.

Refers to #445

**Comment by jefersonf** [comment]
I'll sort this out to get started.

**Comment by IonesioJunior** [comment]
Cool! It's yours:)
