### ISSUE TITLE
Plan Download

### ISSUE THREAD

**Issue by IonesioJunior** [OpenMined/PyGrid#465]
## Plan Download

**THIS ENDPOINT IS HTTP ONLY.**

**HTTP endpoint**: `GET /federated/get-plan`
**Query string**: `?worker_id=ID OF THE WORKER&request_key=LONG HASH VALUE&plan_id=ID OF THE PLAN&receive_operations_as=list`

This method will allow a worker that has been accepted into a cycle to request the download of a plan from PyGrid. They need to submit their `request_key` provided in the cycle request call above. This provides an extra means of authentication for PyGrid to ensure it's sending data to the right worker.

The worker also needs to specify how the worker likes to receive plans: either a list of operations (`"list"`) or TorchScript (`"torchscript"`) depending on the type of worker requesting (https://github.com/OpenMined/PyGrid/issues/437). This is found in the `receive_operations_as` key of the request data.

Response: _This downloads the plan to the worker._

Refers to #445

**Comment by Benardi** [comment]
I would like to work on this one

**Comment by IonesioJunior** [comment]
Awesome, It's yours!

**Comment by cereallarceny** [comment]
@Benardi Why is this blocked specifically?

**Comment by Benardi** [comment]
> @Benardi Why is this blocked specifically?

Blocked by:
* [PyGrid Issue 437](https://github.com/OpenMined/PyGrid/issues/437)
    + [PySyft Issue 2994](https://github.com/OpenMined/PySyft/issues/2994)
