### ISSUE TITLE
Protocol Download

### ISSUE THREAD

**Issue by IonesioJunior** [OpenMined/PyGrid#466]
## Protocol Download
**THIS ENDPOINT IS HTTP ONLY.**

**HTTP endpoint**: `GET /federated/get-protocol`
**Query string**: `?worker_id=ID OF THE WORKER&request_key=LONG HASH VALUE&protocol_id=ID OF THE PROTOCOL`

This method will allow a worker that has been accepted into a cycle to request the download of a protocol from PyGrid. They need to submit their `request_key` provided in the cycle request call above. This provides an extra means of authentication for PyGrid to ensure it's sending data to the right worker.

Response: _This downloads the protocol to the worker._

Refers : #445

**Comment by joaolcaas** [comment]
Can i get this one?

**Comment by IonesioJunior** [comment]
It's yours!
