### ISSUE TITLE
Report FL Process

### ISSUE THREAD

**Issue by IonesioJunior** [OpenMined/PyGrid#468]
## Report

**HTTP endpoint**: `POST /federated/report`
**Socket type**: `federated/report`
**Request data**:
```json
{
  "worker_id": "ID OF THE WORKER",
  "request_key": "LONG HASH VALUE",
  "diff": "FINAL MODEL DIFF FROM TRAINING"
}
```

This method will allow a worker that has been accepted into a cycle and finished training a model on their device to upload the resulting model diff.

If the worker did not train a protocol to be done after the plan(s) was executed, then they will simply submit their entire model diff. If they want to manually add noise to this diff as a layer of protection, they may do so at the developer's discretion from inside the worker implementation.

If the worker did execute a protocol and they have finished the secure aggregation protocol with other workers, they will now receive a share of the resulting securely aggregated model diff. In this case, they will submit the share of the diff, rather than their original model diff. PyGrid will handle the decryption of the shares once they're all submitted.

Response: `{ "status": "success" }`

The response of success is sent if the response is a 200. **The worker should not be informed if the model diff was accepted or denied as part of the global model update.**

Refers to #445

**Comment by joaolcaas** [comment]
Can i take it?
