### ISSUE TITLE
Syft messaging has no attribute 'plan'

### ISSUE THREAD

**Issue by DanielMorales9** [OpenMined/PyGrid#491]
I get this problem when connecting to the WebSocketGridClient.  
Can anyone help me with this issue?
```
File "/usr/local/lib/python3.7/site-packages/grid/__init__.py", line 3, in <module>
   from grid.websocket_client import WebsocketGridClient
File "/usr/local/lib/python3.7/site-packages/grid/websocket_client.py", line 30, in <module>
    class WebsocketGridClient(WebsocketClientWorker, FederatedClient):
File "/usr/local/lib/python3.7/site-packages/grid/websocket_client.py", line 478, in WebsocketGridClient
    def serve_encrypted_model(self, encrypted_model: sy.messaging.plan.Plan) -> bool:
AttributeError: module 'syft.messaging' has no attribute 'plan'
```

**Comment by karlhigley** [comment]
@DanielMorales9 Grid needs to be updated to reflect recent changes in PySyft and the Syft protocol schemas. I'll look into it.

**Comment by karlhigley** [comment]
@DanielMorales9 Actually, I can't find the code referenced in the stack trace in the current versions of either PySyft or PyGrid. Could you try updating to the latest versions?

**Comment by karlhigley** [comment]
It looks like that code was deprecated and later removed in #476, which [suggests](https://github.com/OpenMined/PyGrid/commit/2b543d075b86a6846d815ab5bdba45b551f48654#diff-b1ef8a3aed029ba9fb6663df43b6c7daL16) using PySyft's `syft.grid` module instead.

**Comment by DanielMorales9** [comment]
Hi @karlhigley, thank you for replying. 
I will let you know whether migrating PyGrid was successful or not. 
Do you also know what torch version I should use?

**Comment by karlhigley** [comment]
👍 

The latest PySyft uses Torch 1.4.

**Comment by DanielMorales9** [comment]
It works, thank you so much 💯
