### ISSUE TITLE
FL Cycle Request improvement

### ISSUE THREAD

**Issue by vvmnnnkv** [OpenMined/PyGrid#514]
**Is your feature request related to a problem? Please describe.**
1. When error occurs during cycle-request, it still returns status: "rejected".
2. When model is fully trained (all num_cycles done), "timeout" is not needed.

**Describe the solution you'd like**
1. Make it consistent with other errors (I think it's just "error" field in the response)
2. Remove "timeout" field? Keep only:
```
{
  status: "rejected"
}
```

**Describe alternatives you've considered**
2. Maybe we could invent some other special status for that case, not sure.
```
{
  status: "no more work for the model :)"
}
```

**Additional context**
Parent issue: https://github.com/OpenMined/PyGrid/issues/445

**Comment by IonesioJunior** [comment]
Thanks @vvmnnnkv , I'll take a look.
