### ISSUE TITLE
Issue Installing Pygrid on Mac with Docker method

### ISSUE THREAD

**Issue by ccurelea** [OpenMined/PyGrid#530]
I am having a little issue with installing the pygrid platform on my local computer and I wanted to know where I should get support for this?  I am running mac os 10.13.6 and i followed these instructions https://github.com/OpenMined/PyGrid. I used the docker method. I pulled and ran openmined/grid-node then changed the etc/hosts file to include 127.0.0.1 host.docker.internal. then I navigated to pysyft/examples/tutorials/websocket/deploy_workers and ran $ docker-compose -f docker-compose.yml up. There is no -mac version so i changed the command to just docker-compose.yml. I get the docker container running as seen in the photo. But when I try to connect through the sample notebook i get 'connection refused error' as seen in photo.
![Screen Shot 2020-03-28 at 1 59 52 PM](https://user-images.githubusercontent.com/47864152/77838994-0349b400-7147-11ea-92d9-98937822a268.png)
![Screen Shot 2020-03-28 at 2 05 49 PM](https://user-images.githubusercontent.com/47864152/77838995-05137780-7147-11ea-8490-ba7301c1ae0c.png)

**Comment by ccurelea** [comment]
Thanks for any help guys! I wanna start contributing!

**Comment by IonesioJunior** [comment]
Hello @ccurelea, I'm glad that you're interested to contribute with us!
The problem pointed out has probably already been solved by PR #534  and #533.
Could you try again and give us a feedback?
