### ISSUE TITLE
Tests for JWT in static FL

### ISSUE THREAD

**Issue by Prtfw** [OpenMined/PyGrid#541]
**Is your feature request related to a problem? Please describe.**
the tests needed are spec-ed out here: https://github.com/OpenMined/PyGrid/pull/539/files#diff-467d6d48965918b3a2013825250e9924R331

**Describe the solution you'd like**
Please see the above

**Describe alternatives you've considered**
we must write tests... no alternatives

**Additional context**
Please contact @Prtfw @hericlesme or @IonesioJunior if you get blocked or need help... (on slack)

**Comment by Prtfw** [comment]
+ zarreen.naowal.reza@gmail.com

**Comment by znreza** [comment]
Hello, I am Zarreen. I would like to work on this issue. Could you please assign this issue to me? My Email address zarreen.naowal.reza@gmail.com.

**Comment by Prtfw** [comment]
@znreza welcome! all yours.

**Comment by Prtfw** [comment]
WIP pr is here: https://github.com/OpenMined/PyGrid/pull/574 
Pending reivews.

**Comment by cereallarceny** [comment]
PR is dead. **This issue is available and up for grabs!**

**Comment by ramesht007** [comment]
Hey,
@cereallarceny can I work on this

**Comment by Prtfw** [comment]
@ramesht007 go for it, there has been some prior work. please feel free to ping me on slack so I can loop you in.

**Comment by ramesht007** [comment]
Thanks @Prtfw

**Comment by cereallarceny** [comment]
Likewise @ramesht007, please reach out to @hericlesme on Slack for questions about this. He is currently working on fixing some issues with this logic and will be of great help to you.

**Comment by ramesht007** [comment]
Sure @cereallarceny

**Comment by MasiMasinga** [comment]
Can I try work on this issue?

**Comment by Prtfw** [comment]
@MasiMasinga all yours! 👍 
If you get stuck / need clarifications... feel free to ping @znreza (she's started some work on this, has familiarity with the code / test cases) or @hericlesme (pygrid expert) or me about this issue.

**Comment by madhavajay** [comment]
Complete
