### ISSUE TITLE
Empty Search Results

### ISSUE THREAD

**Issue by patselle** [OpenMined/PyGrid#547]
Hi,

I'm trying to work through your tutorials.
I keep running into the same problem: After I perform a search for the tags in the grid, the results are empty. 
This happens to me in Part3 or in MNIST tutorial.

About the setup,
in the background I run the necessary components (gateway, bill, and so on). These, I launch with docker-compose up in the PyGrid directory.

Did I make a mistake somewhere?

**Comment by IonesioJunior** [comment]
Hello @patselle, your problem may be related to an error in the Redis management code that we are working to fix. Deleting the "**REDISCLOUD_URL**" environment variable in the docker-compose file will likely solve the problem temporarily.

**Comment by patselle** [comment]
Hi @IonesioJunior, 
works, thank you.

Patrick
