### ISSUE TITLE
Translate examples to your native language!

### ISSUE THREAD

**Issue by UtkarshChaurasia** [OpenMined/PyGrid#558]
At present, our examples notebook series is only available in English, but it would be very desirable for people to be able to learn PyGrid in their native language

For this PR, copy the current notebooks and translate the inline text to a language you know, create a folder named "translations" in the "examples" folder and create a folder according to name of the language inside the "translation" folder and place the notebooks in that folder.

Rule: 
Only translate English which is in the notebook or generated from code in the notebook. Any English which is coming from the PyGrid itself (such as error messages) should remain in English.

**Comment by UtkarshChaurasia** [comment]
Can I start with translations in hindi?? @IonesioJunior

**Comment by IonesioJunior** [comment]
Yep, go ahead please! :)

**Comment by UtkarshChaurasia** [comment]
@IonesioJunior I have created a PR for adding Hindi translations of examples.
