### ISSUE TITLE
Creating GridPlatform with Pygrid.

### ISSUE THREAD

**Issue by maddy023** [OpenMined/PyGrid#563]
hello Pygrid team,

After playing with virtual workers,i actually need to create grid platform with specific machines as my workers through in my network.
How to setup node and publicgridnetwork with pygrid (without docker )?

step 2 from below link:
https://blog.openmined.org/what-is-pygrid-demo/

**Comment by jmaunon** [comment]
Take a look to https://github.com/OpenMined/PyGrid/. These are the "real" workers where data lives
