### ISSUE TITLE
Update tutorials

### ISSUE THREAD

**Issue by jmaunon** [OpenMined/PyGrid#564]
PyGrid  depends a lot on PySyft and GridNode.

This impact in the tutorials, some of them are outdated.

The tutorials should be updated :)

**Comment by imidex-jake** [comment]
Can I be assigned to this?

**Comment by eric-yates** [comment]
Can I be assigned to this?

**Comment by jmaunon** [comment]
Any update?

**Comment by eric-yates** [comment]
Woops this fell of my radar! I'll work on updating the second tutorial this week.

**Comment by jmaunon** [comment]
> Woops this fell of my radar! I'll work on updating the second tutorial this week.

Nice. Let me know if you need help. I guess some points will fail...
