### ISSUE TITLE
Create a better Readme

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGrid#568]
[Based on this readme template](https://github.com/OpenMined/.github/blob/master/README-TEMPLATE.md), we should improve our readmes across all OpenMined projects.

[Please consult the following document for our desired best practices.](https://docs.google.com/document/d/126smq1Gful_mo-x5Wm1M1UJW9CvB8fT9YYZmamNqk0M/edit?usp=sharing)

**Comment by eric-yates** [comment]
What do you think about adding information to the template about how to properly fork repos and create pull requests? [Here's a possible example](https://gist.github.com/Chaser324/ce0505fbed06b947d962).

**Comment by Benardi** [comment]
> What do you think about adding information to the Contributing section about how to properly fork repos and create pull requests? [Here's a possible example](https://gist.github.com/Chaser324/ce0505fbed06b947d962).

I think that this sort of information would be a particularly helpful addition to the Contributing section. On the other hand we face the risk of a lengthy Contributing section that no one will read. A solution would be to link to such information in the Contributing section.

**Comment by eric-yates** [comment]
Used the template you provided in #570, in response to a request from Trask to create a new docs directory for each project.

**Comment by cereallarceny** [comment]
@iamtrask this stale bot is getting out of hand. This is probably the fourth time I’ve had to unmark a legitimate issue as stale. Can this be customized in any way?

**Comment by jmaunon** [comment]
@cereallarceny . I will take this issue
