### ISSUE TITLE
Reorganization of PyGrid for better scalability

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGrid#578]
## What?
We would like to reorganize how PyGrid is structured so that it has the ability to scale horizontally more easily in the future. [Please reference this sub-roadmap for more information.](https://github.com/OpenMined/Roadmap/blob/master/web_and_mobile_team/projects/common/pygrid_reorganization.md)

## Why?
~Currently, PyGrid is set up to host data on databases tied to VirtualWorkers. This means that as you want to add more computational power (vertical scaling) or add more workers (horizontal scaling) that your database will likely be affected by such changes. Instead, it's more common to have a centralized database associated with something we're calling the "Gateway". In this new model, "Nodes" (VirtualWorkers performing tasks at the edge) will be fed data (from a database) and instructions (a plan) **from the Gateway** and will simply fulfill the function of a worker. They do not have any private data or models associated with them. The Gateway, instead, will function as a load balancer for the various Nodes. On top of a Gateway will be a "Network" which is basically a way of querying multiple Gateways simultaneously. A Network is an optional component and it doesn't act as a load balancer.~

~For example, let's say a hospital wants to host private data in PyGrid for dynamic federated learning. They would create their own Gateway and provision compute Nodes underneath it. The data is stored in a single, central database connected only to the Gateway. The hospital may be part of a Network of other hospitals, each with its own private Gateway. They may be searched by a data scientist **either** at the Gateway-level, or at the Network-level.~

**See comments below, as well as read the roadmap posted above.**

## Breakdown
I will rely on @IonesioJunior to fill out this section on his own, as he understands the current infrastructure needs better than anyone.

## Additional Context
[Please read this document thoroughly.](https://github.com/OpenMined/Roadmap/blob/master/web_and_mobile_team/projects/common/pygrid_reorganization.md)

**Comment by IonesioJunior** [comment]
@cereallarceny  Please, correct me if I'm mistaken. This issue should be moved to the GridNode repository, shouldn't it?

**Comment by cereallarceny** [comment]
You could @IonesioJunior, but I don't think it's necessary. To me there's only one issue here that hasn't been done. We need to make "Workers" their own repository and allow them to deployed as individual machines, rather than VirtualWorkers on the same machine as the Node. That's the only change. If you want to move the issue that's fine.

**Comment by cereallarceny** [comment]
This issue is irrelevant due to a few other issues being created. Closing.
