### ISSUE TITLE
Tutorials are referencing PyGrid/app/websocket/ which isn't found

### ISSUE THREAD

**Issue by youben11** [OpenMined/PyGrid#579]
## Where?
Tutorials about starting websocket_app

## What?
Where the app should be found

## Additional Context
I need to start different workers by customizing the started script

**Comment by hobe-dev** [comment]
I believe this is covered in https://github.com/OpenMined/PyGrid/pull/571 - we should try to get this merged - someone has a similar issue brought up as well
