### ISSUE TITLE
Do not reject from cycle request if server_config.num_cycles = 0

### ISSUE THREAD

**Issue by Prtfw** [OpenMined/PyGrid#587]
## Feature Description
For development and inference, we want to be able to download a model immediately 
Proposed solution:
1. if server_config.num_cycles = 0, this acts like a flag for pygrid to accept all cycle requests.
2. how model diff averaging would work: immediately average after server_config.min_worker number of diffs has been received. if doing development / testing, set the server_config.min_worker = 1 is equivalent to federated averaging with yourself (effectively no averaging at all but the model will still learn using fed learning mechanism end to end)

## Is your feature request related to a problem?
see above

## What alternatives have you considered?
n/a this is just a quick solution to help speed up development and allow inference.

**Comment by IonesioJunior** [comment]
Yoo @Prtfw, could you add `priority/severity` labels on this issue? Just to make the task evaluation easier to reallocate efforts. :)

**Comment by Prtfw** [comment]
@IonesioJunior I added : ) also I will likely end up working on this.
