### ISSUE TITLE
Intelligent worker selection is not wired to cycle request endpoint

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGrid#589]
## Description
We have an intelligent worker selection algorithm that remains unhooked to the actual cycle request endpoint. @Prtfw wrote this and we need someone to hook it up. Any takers?

## Are you interested in working on this improvement yourself?
- No, but I think @Prtfw  would be interested.

## Additional Context
N/A

**Comment by Prtfw** [comment]
this is a equivalent issue to https://github.com/OpenMined/PyGrid/issues/550
