### ISSUE TITLE
Static FL cycles do not end

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGrid#591]
## Description
Currently, static FL cycles do not end because the `cycle_length` variable on the `server_config` is not used. We need to use that variable to appropriately end the cycle and start a new one as needed.

## Are you interested in working on this improvement yourself?
- No, I am not.

## Additional Context
N/A

**Comment by vvmnnnkv** [comment]
@cereallarceny 
Note: cycles do end after # of updates reaches `max_workers`, but I think `max_workers` means max number of concurrent workers accepted into a cycle?

**Comment by cereallarceny** [comment]
That’s correct. My mistake @vvmnnnkv
