### ISSUE TITLE
Static FL process rejection should return timeout

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGrid#619]
## Description
Currently, we're not returning a `timeout` variable when a worker is rejected. It should return a timeout in the number of seconds it takes until the next cycle will begin.

## Expected Behavior
See above

## Additional Context
None

**Comment by hericlesme** [comment]
PyGrid currently returns the timeout variable when the cycle is rejected and it is not the last cycle.

```python
response = {
    CYCLE.STATUS: "rejected",
    MSG_FIELD.MODEL: name,
    CYCLE.VERSION: _cycle.version,
}

# If it's not the last cycle, add the remaining time to the next cycle.
if n_completed_cycles < _max_cycles:
    remaining = _cycle.end - datetime.now()
    response[CYCLE.TIMEOUT] = str(remaining)
```
