### ISSUE TITLE
Create User model in Node DB

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGrid#630]
We need to create a model in the database with which to store users. This will enable the PyGrid Admin UI to allow people to sign in and make changes to the PyGrid Node, its Workers, and associated Networks. It will also serve as a storage mechanism for data scientists to create accounts and make training and inference requests, permissions change requests, and environment allocation requests.

- The table name should not be prefixed to static or dynamic FL: the name should be exactly "**user**". This is because it's the same table that will store data for admins to manage the static and the dynamic process, even if data scientists created in this table only have access to the dynamic process.

Here are the fields we need:
- **id** - integer, primary key, autoincrement
- **email** - string
- **hashed_password** - string
- **salt** - string
- **private_key** - string
- **role** - role
- **groups** - group[]

Note, you'll need to create the [role table](https://github.com/OpenMined/PyGrid/issues/631) and the [group table](https://github.com/OpenMined/PyGrid/issues/632) before doing this issue.

**Comment by Benardi** [comment]
@cereallarceny The way see this `groups` column (a list of foreign keys) denotes a **many-to-many** relationship because a user may be related to multiple groups and the same group may link multiple users. 

In the realm of SQL a **many-to-many** relationship would entail a junction table. Do you see another path ?

**Comment by cereallarceny** [comment]
You're correct. I didn't see this - my mistake. Create the junction table.
