### ISSUE TITLE
Create Node API endpoints for Groups

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGrid#635]
We need a variety of API endpoints for groups so that we can easily group data scientists the PyGrid application. Here are a few commonalities between all endpoints:

- All endpoints should be supported in both HTTP and Websockets. Please follow the same organizational structure and workflow that was used in the static FL project for this.
- Successful returns should send back the group object itself.
- Note that on these API routes, there is no `static` or `dynamic` prefix. This is because this table is shared between both workflows, and therefore the API endpoints should follow the same methodology.

### Create Group - `POST /groups`
**Request body:** `name`
**Description:** Creates a new group. Only users with the permission of `can_create_groups` can create a group. Duh.

### Get Group - `GET /groups/{id}`
**Request body:** N/A
**Description:** Gets an individual group. Only users with the permission of `can_triage_jobs` can get a group.

### Get Groups - `GET /groups`
**Request body:** N/A
**Description:** Gets all groups. Only users with the permission of `can_triage_jobs` can get all groups.

### Update Group - `PUT /groups/{id}`
**Request body:** `name`
**Description:** Updates a group. Only users with the permission of `can_create_groups` can edit a group.

### Delete Group - `DELETE /groups/{id}`
**Request body:** N/A
**Description:** Deletes a group. Only users with the permission of `can_edit_groups` can delete a group.

**Comment by Benardi** [comment]
@cereallarceny  There was no `can_edit_groups` field in the Role model for the Node. https://github.com/OpenMined/PyGrid/issues/631
(Or the Network for that matter https://github.com/OpenMined/PyGrid/issues/637)

Did you mean `can_create_groups` or is this a correction we should pursue ?
