### ISSUE TITLE
Create User model in Network DB

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGrid#638]
We need to create a model in the database with which to store users. This will enable the PyGrid Admin UI to allow people to sign in and make changes to the PyGrid Network.

- The name should be exactly "**user**".

Here are the fields we need:
- **id** - integer, primary key, autoincrement
- **email** - string
- **hashed_password** - string
- **salt** - string
- **role** - role

Note, you'll need to create the [role table](https://github.com/OpenMined/PyGridNetwork/issues/48) before doing this issue.

**Comment by Benardi** [comment]
@cereallarceny I assume the column role is a `foreign key` to the table Role, is that correct ?

**Comment by cereallarceny** [comment]
Correct @Benardi. You can assume that for all the diagrams and issues going forward.
