### ISSUE TITLE
how to visualize the progress of the federated learning

### ISSUE THREAD

**Issue by pengyuan-zhou** [OpenMined/PyGrid#641]
Hi all,
I'm running the federated learning scripts and the terminal does show the progress as follows.
```
gateway_1  | INFO:root:# of diffs: 1
gateway_1  | INFO:root:ready_to_average: 1
gateway_1  | INFO:root:start diffs averaging!
gateway_1  | INFO:root:cycle: < Cycle id : 5, sequence: 5, start: 2020-07-18 09:54:24.122128, end: 2020-07-18 17:54:24.122128, fl_process_id: 1, is_completed: False>
gateway_1  | INFO:root:fl id: 1
gateway_1  | INFO:root:model: <Model  id: 1, version: None>
gateway_1  | INFO:root:model id: 1
gateway_1  | INFO:root:current checkpoint: <CheckPoint id: 5, model_id: 1>
gateway_1  | INFO:root:model params shapes: [torch.Size([392, 784]), torch.Size([392]), torch.Size([10, 392]), torch.Size([10])]
gateway_1  | INFO:root:Doing hosted avg plan
gateway_1  | INFO:root:diff_avg shapes: [torch.Size([392, 784]), torch.Size([392]), torch.Size([10, 392]), torch.Size([10])]
gateway_1  | INFO:root:_updated_model_params shapes: [torch.Size([392, 784]), torch.Size([392]), torch.Size([10, 392]), torch.Size([10])]
gateway_1  | INFO:root:new checkpoint: <CheckPoint id: 6, model_id: 1>
gateway_1  | INFO:root:completed_cycles_num: 5
gateway_1  | INFO:root:FL is done!
```
but when open the url of the workers, nothing is there, as shown in the fig.
<img src="https://user-images.githubusercontent.com/20013315/87850964-ec4cee80-c8fc-11ea-9f80-33bdb31d2504.png" width="400">
Any suggestion is appreciated.
Thank you.

**Comment by cereallarceny** [comment]
There currently isn't a way to visualize this @pengyuan-zhou. It will be added over the next few months (screenshots here: https://github.com/OpenMined/Roadmap/blob/master/web_and_mobile_team/projects/common/pygrid_admin.md). Here's our roadmap for dynamic FL (you're going static FL), but it will also include many tasks for static FL, including making a UI: https://github.com/OpenMined/Roadmap/blob/master/web_and_mobile_team/projects/dynamic_federated_learning.md

**Comment by cereallarceny** [comment]
Closing this as this has already been answered and there won't be an update for a while.

**Comment by pengyuan-zhou** [comment]
> https://github.com/OpenMined/Roadmap/blob/master/web_and_mobile_team/projects/common/pygrid_admin.md

Great, thanks for the notification, is there currently any command to interactively monitor the progress other than staring  at the pygrid running terminal lol?

**Comment by cereallarceny** [comment]
There isn't currently, it's on our 0.3.0 milestone to deliver this via CLI and Python client. However, in the future you can manage and view the entire process from a UI.
