### ISSUE TITLE
Fail in running tutorial

### ISSUE THREAD

**Issue by a8252525** [OpenMined/PyGrid#669]
## Description
While I was running the example [Part 2 - Launch a PyGrid Network Locally](https://github.com/OpenMined/PyGrid/blob/dev/examples/Part%202%20-%20Launch%20a%20PyGrid%20Network%20Locally.ipynb)
I fail in using  PublicGridNetwork.search().

## How to Reproduce
1. Git clone the PyGrid repo
2. cd PyGrid and run the docker-compose.yml to start the grid-node and grid-gateway docker
3. docker exec -it pygrid_gateway_1 bash 
4. ./dev_server.sh 
5. run the  [Part 2 - Launch a PyGrid Network Locally](https://github.com/OpenMined/PyGrid/blob/dev/examples/Part%202%20-%20Launch%20a%20PyGrid%20Network%20Locally.ipynb)

## Expected Behavior
I expect  that the PublicGridNetwork.search() get the tensor I sent since I successfully sent the data to the grid node.

## Screenshots
![image](https://user-images.githubusercontent.com/32895524/88256761-ab831a00-ccee-11ea-9417-337e72d501b6.png)

## System Information
 - OS: Ubuntu 18.04
 - Language Version: Python 3.6.9,  Syft 0.2.6, syft-proto 0.4.10
 - Package Manager Version: pip 20.0.2

## Additional Context
I am new in syft and pygrid, so I am not sure whether I have missed anything or not. Any response will be appreciated.

**Comment by jmaunon** [comment]
Thanks for openning  the issue. This is a known issue and hopefully documentation and tutorials will be updated soon.

**Comment by xujialiang** [comment]
> ## Description
> While I was running the example [Part 2 - Launch a PyGrid Network Locally](https://github.com/OpenMined/PyGrid/blob/dev/examples/Part%202%20-%20Launch%20a%20PyGrid%20Network%20Locally.ipynb)
> I fail in using PublicGridNetwork.search().
> 
> ## How to Reproduce
> 1. Git clone the PyGrid repo
> 2. cd PyGrid and run the docker-compose.yml to start the grid-node and grid-gateway docker
> 3. docker exec -it pygrid_gateway_1 bash
> 4. ./dev_server.sh
> 5. run the  [Part 2 - Launch a PyGrid Network Locally](https://github.com/OpenMined/PyGrid/blob/dev/examples/Part%202%20-%20Launch%20a%20PyGrid%20Network%20Locally.ipynb)
> 
> ## Expected Behavior
> I expect that the PublicGridNetwork.search() get the tensor I sent since I successfully sent the data to the grid node.
> 
> ## Screenshots
> If applicable, add screenshots to help explain your problem.
> ![image](https://user-images.githubusercontent.com/32895524/88256761-ab831a00-ccee-11ea-9417-337e72d501b6.png)
> 
> ## System Information
> * OS: Ubuntu 18.04
> * Language Version: Python 3.6.9,  Syft 0.2.6, syft-proto 0.4.10
> * Package Manager Version: pip 20.0.2
> 
> ## Additional Context
> I am new in syft and pygrid, so I am not sure whether I have missed anything or not. Any response will be appreciated.

I got the same error

**Comment by jmaunon** [comment]
Tutorials have been updated
