### ISSUE TITLE
Model-centric websockets to support concurrent requests

### ISSUE THREAD

**Issue by vvmnnnkv** [OpenMined/PyGrid#685]
## What?
Ensure that model-centric websockets API is capable to support multiple concurrent requests using a single connection so that the client can distinguish which response is related to which request.

## How long?
Ideally we have unit test that checks that.

## Is your research related to a problem?
See
https://github.com/OpenMined/KotlinSyft/issues/235
https://github.com/OpenMined/SwiftSyft/issues/170

**Comment by vkkhare** [comment]
So all we need to do is add the response handlers like job name and version whenever needed. I will update the responses here for evaluation

**Comment by vvmnnnkv** [comment]
Upd: As discussed, we can add `id` or `req_id` (or similar param in every request) and copy its convents back into corresponding response . This will allow worker to correspond every res to req via this id.
