### ISSUE TITLE
DataCentricFLClient memory leak

### ISSUE THREAD

**Issue by KCC13** [OpenMined/PyGrid#695]
## Description
Allocated memory is not released after `.get()` when using DataCentricFLClient.

## How to Reproduce
1. Launch PyGrid Node `./run.sh --id bot001 --host 127.0.0.1 --port 8777 --start_local_db`.
2. Run `free -m -s 5` to monitor memory usage
3. Run the following code
```python
import torch
import syft as sy
from syft.grid.clients.data_centric_fl_client import DataCentricFLClient

hook = sy.TorchHook(torch)
device = torch.device("cpu")
worker = DataCentricFLClient(hook, "ws://localhost:8777")

x = torch.zeros(1000, 1000).to(device)
while True:
	x_copy = x.copy()
	x_ptr = x_copy.send(worker)
	x_ptr.get()
```
4. The amount of free memory decreases continuously

## Expected Behavior
Memory should be released after `.get()`.
P.S. WebsocketClientWorker works fine (memory usage will keep at a certain level).

## System Information
 - OS: Ubuntu
 - OS Version: 18.04.4 LTS
 - Language Version: Python 3.7.7
 - Package Manager Version: Conda 4.8.2
 - PySyft Version: 0.2.8

## Additional Context
Example for WebsocketClientWorker
```python
import torch
import syft as sy
from syft.workers.websocket_client import WebsocketClientWorker

hook = sy.TorchHook(torch)
device = torch.device("cpu")
worker = WebsocketClientWorker(hook=hook, id="bot001", host="localhost", port=8777)

x = torch.zeros(1000, 1000).to(device)
while True:
	x_copy = x.copy()
	x_ptr = x_copy.send(worker)
	x_ptr.get()
```

**Comment by madhavajay** [comment]
`0.2.x` is no longer supported.
