### ISSUE TITLE
Empty search results

### ISSUE THREAD

**Issue by b02202050** [OpenMined/PyGrid#697]
## Question
After launching the docker compose and sending a tensor to a node, I still can not search the sent tensor.

## Further Information
I use two PCs.
One of the PC's IP is 192.168.51.189 and is launched with `sudo docker-compose up` with PyGrid commit sha *996b6ab*
The other PC's IP is 192.168.51.177 and the environment is the docker image: `openmined/pysyft-notebook`.
I run the code on the second PC with the following code:
![image](https://user-images.githubusercontent.com/35265996/90361502-f8a9a000-e090-11ea-8145-92520bc71852.png)
Is there somewhere I missed to do?

Thanks very much for helping!

**Comment by jmaunon** [comment]
Could you check nodes are connected? . The endpoint is `connected-nodes`

**Comment by b02202050** [comment]
Thanks for information!
![image](https://user-images.githubusercontent.com/35265996/90458960-6bb72300-e132-11ea-9a05-5a4b49e779e0.png)
My nodes are indeed not connected, but how to connect the nodes?
Isn't `sudo docker-compose up` enough?

**Comment by b02202050** [comment]
> @b02202050 Have you been able to find a solution to this issue? I am facing the same issue.

@hammad45 Sorry I'm still stuck.
I'll be glad if you find a solution.
Thanks!

**Comment by jmaunon** [comment]
requests.post( os.path.join(_network, "join"), data=json.dumps( {"node-id": args.id, "node-address": "{}".format(_address)} ), )

**Comment by b02202050** [comment]
@jmaunon 
Thanks again!
but I still get a bad request when searching.
I Try the following code:
```python
_network = 'http://192.168.51.189:5000'
node_id = 'Alice'
_address = 'ws://192.168.51.189:3000'
r = requests.post(os.path.join(_network, 'join'), data=json.dumps( {"node-id": node_id, "node-address": "{}".format(_address)} ), )
# >>> r.content
# >>> b'{"message": "Successfully Connected!"}'
# >>> requests.get('http://192.168.51.189:5000/connected-nodes').content
# >>> b'{"grid-nodes": ["0", "node_id", "alice", "Alice"]}' # I tried several names
grid.search('#my_tag1')
```
and I get:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-52-da9c779e928c> in <module>
----> 1 grid.search('#my_tag1')

/opt/conda/lib/python3.7/site-packages/syft/grid/public_grid.py in search(self, *query)
     38         tensor_results = {}
     39         #print(match_nodes)
---> 40         for node_id, node_url in match_nodes:
     41             worker = self.__connect_with_node(node_id, node_url)
     42             tensor_results[node_id] = worker.search(query)

ValueError: too many values to unpack (expected 2)
```
Afterward I tried:
```python
r = requests.post('http://192.168.51.189:5000/search', json.dumps({"query": ['#my_tag1']}))
r.content
```
And I get:
```python
b'{"message": "Invalid JSON format."}'
```

What is the reason of the bad request?
Thanks!

**Comment by jmaunon** [comment]
hi @b02202050 , shall we close this issue?

**Comment by b02202050** [comment]
@jmaunon, do you have suggestions about my problem?

**Comment by Qinbf** [comment]
@b02202050 请问你搞定了吗，我也是想你这样的情况

**Comment by Qinbf** [comment]
@hammad45 请问这个问题有新的进展吗

**Comment by b02202050** [comment]
Hi @Qinbf ,
 I removed the old docker image and the repository and pull the latest image and clone the latest repository.
After that, I have no such problem, so I will close this issue.
On the other hand, I have another problem of searching the tensor on the other computer, You can follow [that issue](https://github.com/OpenMined/PyGrid/issues/754).
