### ISSUE TITLE
grid-nodes empty at http://localhost:7000/connected-nodes 

### ISSUE THREAD

**Issue by NazgulLee** [OpenMined/PyGrid#721]
## Description
grid-nodes empty at http://localhost:7000/connected-nodes

## How to Reproduce
1. docker-compose up
2. go to " http://localhost:7000/connected-nodes"
3. display 
```
{
grid-nodes: [ ]
}
```
## Expected Behavior
should display
```
{"grid-nodes": ["Dan", "Alice", "Charlie", "Bob"]}
```
## System Information
 - OS: macOS Catalina
 - OS Version: 10.15.5
 - Browser (if applicable): Safari
 - Browser Version (if applicable):13.1.1
 - Docker Desktop:2.3.0.4

**Comment by li4112** [comment]
I am facing the same issue.
with docker-compose command ,I get:

**Comment by li4112** [comment]
Creating network "pygrid-dev_default" with the default driver
Creating pygrid-dev_network_1 ... done
Creating pygrid-dev_alice_1   ... done
Creating pygrid-dev_bob_1     ... done
Creating pygrid-dev_charlie_1 ... done
Creating pygrid-dev_dan_1     ... done
Creating pygrid-dev_jupyter_1 ... done
Attaching to pygrid-dev_network_1, pygrid-dev_dan_1, pygrid-dev_charlie_1, pygrid-dev_alice_1, pygrid-dev_bob_1, pygrid-dev_jupyter_1
network_1  | [2020-09-16 08:17:02 +0000] [1] [INFO] Starting gunicorn 20.0.4
network_1  | [2020-09-16 08:17:02 +0000] [1] [INFO] Listening at: http://0.0.0.0:7000 (1)
network_1  | [2020-09-16 08:17:02 +0000] [1] [INFO] Using worker: flask_sockets.worker
network_1  | [2020-09-16 08:17:02 +0000] [11] [INFO] Booting worker with pid: 11
dan_1      | [2020-09-16 08:17:08 +0000] [1] [INFO] Starting gunicorn 20.0.4
dan_1      | [2020-09-16 08:17:08 +0000] [1] [INFO] Listening at: http://0.0.0.0:5003 (1)
dan_1      | [2020-09-16 08:17:08 +0000] [1] [INFO] Using worker: flask_sockets.worker
bob_1      | [2020-09-16 08:17:08 +0000] [1] [INFO] Starting gunicorn 20.0.4
bob_1      | [2020-09-16 08:17:08 +0000] [1] [INFO] Listening at: http://0.0.0.0:5001 (1)
bob_1      | [2020-09-16 08:17:08 +0000] [1] [INFO] Using worker: flask_sockets.worker
alice_1    | [2020-09-16 08:17:08 +0000] [1] [INFO] Starting gunicorn 20.0.4
alice_1    | [2020-09-16 08:17:08 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
alice_1    | [2020-09-16 08:17:08 +0000] [1] [INFO] Using worker: flask_sockets.worker
dan_1      | [2020-09-16 08:17:08 +0000] [11] [INFO] Booting worker with pid: 11
charlie_1  | [2020-09-16 08:17:08 +0000] [1] [INFO] Starting gunicorn 20.0.4
charlie_1  | [2020-09-16 08:17:08 +0000] [1] [INFO] Listening at: http://0.0.0.0:5002 (1)
charlie_1  | [2020-09-16 08:17:08 +0000] [1] [INFO] Using worker: flask_sockets.worker
bob_1      | [2020-09-16 08:17:08 +0000] [11] [INFO] Booting worker with pid: 11
alice_1    | [2020-09-16 08:17:08 +0000] [11] [INFO] Booting worker with pid: 11
charlie_1  | [2020-09-16 08:17:08 +0000] [11] [INFO] Booting worker with pid: 11
jupyter_1  | [I 08:17:08.500 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
jupyter_1  | [I 08:17:10.157 NotebookApp] Serving notebooks from local directory: /workspace
jupyter_1  | [I 08:17:10.157 NotebookApp] The Jupyter Notebook is running at:
jupyter_1  | [I 08:17:10.157 NotebookApp] http://172.19.0.7:8888/?token=547493c23caa7a009da0a2557c15d531df3e1804f1a4bc13
jupyter_1  | [I 08:17:10.157 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
jupyter_1  | [W 08:17:10.175 NotebookApp] No web browser found: could not locate runnable browser.
jupyter_1  | [C 08:17:10.175 NotebookApp] 
jupyter_1  |     
jupyter_1  |     To access the notebook, open this file in a browser:
jupyter_1  |         file:///root/.local/share/jupyter/runtime/nbserver-10-open.html
jupyter_1  |     Or copy and paste one of these URLs:
jupyter_1  |         http://172.19.0.7:8888/?token=547493c23caa7a009da0a2557c15d531df3e1804f1a4bc13
dan_1      | WARNING:root:Using default secrect key, this is not safe and should be used only for testing and development. To define a secrete key please define the environment variable SECRET_KEY.
alice_1    | WARNING:root:Using default secrect key, this is not safe and should be used only for testing and development. To define a secrete key please define the environment variable SECRET_KEY.
bob_1      | WARNING:root:Using default secrect key, this is not safe and should be used only for testing and development. To define a secrete key please define the environment variable SECRET_KEY.
charlie_1  | WARNING:root:Using default secrect key, this is not safe and should be used only for testing and development. To define a secrete key please define the environment variable SECRET_KEY.
charlie_1  | INFO:syft:TF Encrypted Keras not available.
alice_1    | INFO:syft:TF Encrypted Keras not available.
dan_1      | INFO:syft:TF Encrypted Keras not available.
bob_1      | INFO:syft:TF Encrypted Keras not available.

**Comment by li4112** [comment]
Browser access       http://192.168.211.100:7000/connected-nodes
response : {"grid-nodes": []}
but ：compute_nodes["Alice"] = DataCentricFLClient(hook, alice_address) 
for key, value in compute_nodes.items(): 
    print("Is " + key + " connected?: " + str(value.ws.connected))

return True

**Comment by li4112** [comment]
@NazgulLee ，你的问题解决了吗？我看你close 了，能分享下怎么解决的吗？

**Comment by Qinbf** [comment]
@li4112 我跟你一样的问题，请问你搞定了吗
