### ISSUE TITLE
docker-compose up Failed

### ISSUE THREAD

**Issue by li4112** [OpenMined/PyGrid#722]
Browser access  http://localhost:7000/connected-nodes 
response : {"grid-nodes": []} 
should display ：{"grid-nodes": ["Dan", "Alice", "Charlie", "Bob"]}

with docker-compose up  command 
i get info ：
Creating network "pygrid-dev_default" with the default driver
Creating pygrid-dev_network_1 ... done
Creating pygrid-dev_alice_1   ... done
Creating pygrid-dev_bob_1     ... done
Creating pygrid-dev_charlie_1 ... done
Creating pygrid-dev_dan_1     ... done
Creating pygrid-dev_jupyter_1 ... done
Attaching to pygrid-dev_network_1, pygrid-dev_dan_1, pygrid-dev_charlie_1, pygrid-dev_alice_1, pygrid-dev_bob_1, pygrid-dev_jupyter_1
network_1  | [2020-09-16 08:17:02 +0000] [1] [INFO] Starting gunicorn 20.0.4
network_1  | [2020-09-16 08:17:02 +0000] [1] [INFO] Listening at: http://0.0.0.0:7000 (1)
network_1  | [2020-09-16 08:17:02 +0000] [1] [INFO] Using worker: flask_sockets.worker
network_1  | [2020-09-16 08:17:02 +0000] [11] [INFO] Booting worker with pid: 11
dan_1      | [2020-09-16 08:17:08 +0000] [1] [INFO] Starting gunicorn 20.0.4
dan_1      | [2020-09-16 08:17:08 +0000] [1] [INFO] Listening at: http://0.0.0.0:5003 (1)
dan_1      | [2020-09-16 08:17:08 +0000] [1] [INFO] Using worker: flask_sockets.worker
bob_1      | [2020-09-16 08:17:08 +0000] [1] [INFO] Starting gunicorn 20.0.4
bob_1      | [2020-09-16 08:17:08 +0000] [1] [INFO] Listening at: http://0.0.0.0:5001 (1)
bob_1      | [2020-09-16 08:17:08 +0000] [1] [INFO] Using worker: flask_sockets.worker
alice_1    | [2020-09-16 08:17:08 +0000] [1] [INFO] Starting gunicorn 20.0.4
alice_1    | [2020-09-16 08:17:08 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
alice_1    | [2020-09-16 08:17:08 +0000] [1] [INFO] Using worker: flask_sockets.worker
dan_1      | [2020-09-16 08:17:08 +0000] [11] [INFO] Booting worker with pid: 11
charlie_1  | [2020-09-16 08:17:08 +0000] [1] [INFO] Starting gunicorn 20.0.4
charlie_1  | [2020-09-16 08:17:08 +0000] [1] [INFO] Listening at: http://0.0.0.0:5002 (1)
charlie_1  | [2020-09-16 08:17:08 +0000] [1] [INFO] Using worker: flask_sockets.worker
bob_1      | [2020-09-16 08:17:08 +0000] [11] [INFO] Booting worker with pid: 11
alice_1    | [2020-09-16 08:17:08 +0000] [11] [INFO] Booting worker with pid: 11
charlie_1  | [2020-09-16 08:17:08 +0000] [11] [INFO] Booting worker with pid: 11
jupyter_1  | [I 08:17:08.500 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
jupyter_1  | [I 08:17:10.157 NotebookApp] Serving notebooks from local directory: /workspace
jupyter_1  | [I 08:17:10.157 NotebookApp] The Jupyter Notebook is running at:
jupyter_1  | [I 08:17:10.157 NotebookApp] http://172.19.0.7:8888/?token=547493c23caa7a009da0a2557c15d531df3e1804f1a4bc13
jupyter_1  | [I 08:17:10.157 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
jupyter_1  | [W 08:17:10.175 NotebookApp] No web browser found: could not locate runnable browser.
jupyter_1  | [C 08:17:10.175 NotebookApp] 
jupyter_1  |     
jupyter_1  |     To access the notebook, open this file in a browser:
jupyter_1  |         file:///root/.local/share/jupyter/runtime/nbserver-10-open.html
jupyter_1  |     Or copy and paste one of these URLs:
jupyter_1  |         http://172.19.0.7:8888/?token=547493c23caa7a009da0a2557c15d531df3e1804f1a4bc13
dan_1      | WARNING:root:Using default secrect key, this is not safe and should be used only for testing and development. To define a secrete key please define the environment variable SECRET_KEY.
alice_1    | WARNING:root:Using default secrect key, this is not safe and should be used only for testing and development. To define a secrete key please define the environment variable SECRET_KEY.
bob_1      | WARNING:root:Using default secrect key, this is not safe and should be used only for testing and development. To define a secrete key please define the environment variable SECRET_KEY.
charlie_1  | WARNING:root:Using default secrect key, this is not safe and should be used only for testing and development. To define a secrete key please define the environment variable SECRET_KEY.
charlie_1  | INFO:syft:TF Encrypted Keras not available.
alice_1    | INFO:syft:TF Encrypted Keras not available.
dan_1      | INFO:syft:TF Encrypted Keras not available.
bob_1      | INFO:syft:TF Encrypted Keras not available.

compute_nodes["Alice"] = DataCentricFLClient(hook, alice_address)
compute_nodes["Bob"]   = DataCentricFLClient(hook, bob_address) 
# Check if they are connected
for key, value in compute_nodes.items(): 
    print("Is " + key + " connected?: " + str(value.ws.connected))
return True 

but : mygrid = PublicGridNetwork(hook, grid_address)
mygrid.search("#Data") 
return empyty

**Comment by jmaunon** [comment]
Please, try to delete the images and build again

**Comment by theactivationfunction** [comment]
On Mac OS X, I also get "No web browser found: could not locate runnable browser." and a 172.18.x.x IP address for the Jupyter Notebook" in the dialogue from docker-compose up...

Per output: "
To access the notebook, open this file in a browser:
jupyter_1  |         file:///root/.local/share/jupyter/runtime/nbserver-10-open.html
jupyter_1  |     Or copy and paste one of these URLs:
jupyter_1  |         http://172.18.0.7:8888/?token=89d289d902261e68954669aea7ed9e7eb9201729f84b69f0
"

Neither of which work (I don't recognise this private IP 172.18.x.x) ??

Browser access http://localhost:7000/connected-nodes
displays ：{"grid-nodes": ["Dan", "Alice", "Charlie", "Bob"]}  

which I assume is OK?

And Jupyter Notebook can be accessed OK via , http://127.0.0.1:8888/tree and 
http://127.0.0.1:8888/notebooks/examples/data-centric/introduction/01-introduction-to-pygrid.ipynb runs without issues.

**Comment by bibs2091** [comment]
try replacing  
http://**172.x.x.x**:8888/?token=06efeae3a9a8c1d368f715bd550851bd42fce6cc5c17c761
with 
http://**localhost**:8888/?token=06efeae3a9a8c1d368f715bd550851bd42fce6cc5c17c761
it should work.

**Comment by nnbtam99** [comment]
> try replacing
> http://**172.x.x.x**:8888/?token=06efeae3a9a8c1d368f715bd550851bd42fce6cc5c17c761
> with
> http://**localhost**:8888/?token=06efeae3a9a8c1d368f715bd550851bd42fce6cc5c17c761
> it should work.

I also encountered this issue and tried this suggested method but it didn't work. Has anybody resolved the problem?
