### ISSUE TITLE
Change all instances of "put" to "update"

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGrid#732]
Currently, our API's on the Node and the Network use a combination of the words "put" and "update" to mean the same thing. We should change all instances of "put" (regardless of lowercase or uppercase) to "update". The one notable exception is in the definition of the type of message in a Flask API: the `put()` method should stay the same because all updates need to actually make a `put()` call.

**Comment by tanmaylaud** [comment]
is this issue resolved ?

**Comment by madhavajay** [comment]
Complete
