### ISSUE TITLE
No results returned from grid.search in tutorial

### ISSUE THREAD

**Issue by socd06** [OpenMined/PyGrid#734]
## Description
Not able to complete [Introductions to PyGrid Tutorial](https://github.com/OpenMined/PyGrid/blob/dev/examples/data-centric/introduction/01-introduction-to-pygrid.ipynb)

## How to Reproduce
1. Follow [Getting Started](https://github.com/OpenMined/PyGrid#Getting%20started) instructions
2. run `docker-compose up` and open Jupyter Notebook instance
3. Execute the cells on [Introductions to PyGrid Tutorial](https://github.com/OpenMined/PyGrid/blob/dev/examples/data-centric/introduction/01-introduction-to-pygrid.ipynb)
4. ... Get no results from `results = grid.search("#February", "#birth-records")
results`

## Expected Behavior
Should be able to complete tutorial successfully 

## Screenshots
![PYGRID-Screenshot from 2020-09-27 13-14-38](https://user-images.githubusercontent.com/51087091/94371497-f6415980-00c4-11eb-8963-85c0400287eb.png)

![PYGRID2Screenshot from 2020-09-27 13-22-45](https://user-images.githubusercontent.com/51087091/94371496-f5a8c300-00c4-11eb-8ca2-dce94f326632.png)

**Comment by jmaunon** [comment]
Please @socd06 , try to remove any previous docker image related to pygrid and build again using `docker-compose up`

**Comment by socd06** [comment]
@jmaunon wow, that fixed it. It seems there's an underlying issue here anyhow, being that the docker images are referred to in the readme but then prevent the `docker-compose` way of running the tutorials. Should I close this or wait for an update?

**Comment by jmaunon** [comment]
I think we can close it, I do not see any issue at this moment. `docker-compose up` works as expected (if not we can always reopen or open a new issue)
