### ISSUE TITLE
What is the difference between a node and a worker?

### ISSUE THREAD

**Issue by sug4ndh** [OpenMined/PyGrid#742]
## Question
What is the difference between a node and a worker?

**Comment by nahuakang** [comment]
Here's an explanation from Patrick:
> Fow now, understand that a PyGrid “Node” is a message forwarding service and an API with an associated database that hosts the data of the data owner, a PyGrid “Worker” is a server entirely dedicated to performing instructions forwarded to it from a PyGrid Node, and a PyGrid “Network” is an optional API layer that allows multiple Nodes to be searched simultaneously.

**Comment by sug4ndh** [comment]
Thanks!

From a more practical point of view, when we run 'PyGrid/apps/node/run.sh' on a system, we are essentially running a messaging forwarding service? Can we have multiple workers on the same system in that case? If yes, then how would we go about creating multiple workers on the same system, by assigning different ids on different ports?
