### ISSUE TITLE
.list_objects_remote() allows to see private tensors

### ISSUE THREAD

**Issue by tyoc213** [OpenMined/PyGrid#746]
## Description
I think the bug reported at https://github.com/OpenMined/PySyft/issues/4594 is a pygrid error, because what is printed is a string (not really a vector) AFAIK, so anyone that knows the protocol could ask for this description and get the private contents.

## How to Reproduce
You can check the linked https://gist.github.com/tyoc213/a41db571f12a983812fa55ecdb93b951 that is also in the other report.

## Expected Behavior
Thrown an error on the client or return something that doesnt contain the private descriptions of private tensors??? (being new on this, Im not sure be the answer, but I think it should not be the contents of the private tensors... their length or data).

## System Information
docker image from like a week a go.

## Additional Context

I think I can solve this error in pygrid, I have already located the `/search` [handler](https://github.com/OpenMined/PySyft/issues/4594#issuecomment-706626287) (with some extra notes and some of the pointers that lead me to move it here) and have been able to change it (thought I need to shutdown and restart the docker images to see the change, if you know a way to reload without restart it would be appreciated).

I also dont know what things should I add in server side to raise the error on the client... or how this should be handled? but I think I can solve if provided with some guidance.

-------------------

I report this here because I think Im stall waiting for extra info... so I decide to take next step that for me is report it here and ask on guidance to submit patch here.

**Comment by madhavajay** [comment]
`0.2.x` is no longer supported.
