### ISSUE TITLE
PyGrid network search error：too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by graduter** [OpenMined/PyGrid#747]
## Description
 install docker, and executer docker-compose up, run container；
Follow the quick start document：
https://github.com/OpenMined/PyGrid/blob/dev/examples/data-centric/introduction/01-introduction-to-pygrid.ipynb 

`
from syft.grid.public_grid import PublicGridNetwork

grid = PublicGridNetwork(hook, grid_address)
grid.search("#February", "#birth-records")

`

error：
![image](https://user-images.githubusercontent.com/8439593/97263613-4e9f7e80-185e-11eb-9682-58fd5a420dfd.png)

**Comment by myhonest86** [comment]
I also get the same error as above.
Are there any activities on issue resolution?

**Comment by madhavajay** [comment]
`0.2.x` is no longer supported.
