### ISSUE TITLE
Use of Private_tensors with PyTorch model

### ISSUE THREAD

**Issue by tristancabel** [OpenMined/PyGrid#749]
## Question
Hello,
I am trying to use PySyft + PyGrid with *private_tensors* and a PyTorch model, but I have strange errors. (it's working without private_tensors)

## Further Information
I set up the data following this example: https://github.com/OpenMined/PyGrid/blob/dev/examples/data-centric/introduction/01-introduction-to-pygrid.ipynb ( Data Owner steps 1 to 6) 

I then try to replace the basic function **sum_column** (defined in the Data Scientist part *Step 5: Perform your computations* ) by a basic Pytorch model like this:

```
class Net(th.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = th.nn.Linear(3, 1)

    def forward(self, x):
        x = self.fc1(x)
        return x

model = Net()
model.send(feb_records.location)
res = model(feb_records)
```

and the node crashes with messages like this:
```
  File "/home/trcabel/miniconda3/envs/fedbiomed/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook_args.py", line 27, in <genexpr>
    else (_ for _ in ()).throw(PureFrameworkTensorFoundError),
syft.exceptions.PureFrameworkTensorFoundError
```

## Additional Context
- I can use the model with dummy data having the same shape as the dataset
- if the dataset is not a private_tensor, the code is working fine
- if the model is just  th.nn.Identity  , the code is working fine

Would you have any idea of what is happening?
Thanks.

**Comment by madhavajay** [comment]
`0.2.x` is no longer supported. Please refer to the new `0.5` release.
