### ISSUE TITLE
Postgres databse for gateway - psycopg2 missing in dependencies

### ISSUE THREAD

**Issue by MariusKempf** [OpenMined/PyGrid#753]
We wanted to use a postgres database instead of the default sqlite for the gateway and the nodes. For the nodes it was not a problem but for the gateway. When comparing the two dockerfiles I found, that the node installs the but the gateway is not.

In the gateway's `network/pyproject.toml` the dependency `psycopg2-binary = "^2.8.5"` is missing ([tool.poetry.dependencies]) while in the `node/pyproject.toml` it is available. That led to my mistake, that psycopg2 module is missing.

Assuming that was by mistake, it would be great to fix that and include psycopg2 for both.

## Additional Context

I fixed it for myself by updating the `pyproject.toml`, (installing poetry), poetry update (to update the lock file) and building my own container-version.

**Comment by madhavajay** [comment]
Resolved with SQLAlchemy.
