### ISSUE TITLE
How to search the tensor on the other computer?

### ISSUE THREAD

**Issue by b02202050** [OpenMined/PyGrid#754]
## Question
How to set the network or port to let the tensor searchable from the other computer.

## Further Information
I have two computers which have local ip 192.168.51.177 and 192.168.51.189.
I ran `docker-compose up` on 192.168.51.189 successfully.
On 192.168.51.189, I can search a tensor that is sent to *Alice* on the 192.168.51.189 like the following.
![image](https://user-images.githubusercontent.com/35265996/100563528-8e440500-32f9-11eb-967f-9780768ae712.png)

On 192.168.51.177, I cannot search the tensor that has been sent.
![image](https://user-images.githubusercontent.com/35265996/100563839-63a67c00-32fa-11eb-91e9-db8aae07addb.png)

## System Information
 - OS: Ubuntu 18.04
 - Package Manager Version: 
     - PyGrid: commit bc9723f9ca2286a28a5f6ff6b9bd500c861d7531 (HEAD -> dev

## Additional Context
Thanks for the help very much if PyGrid can be run on two computers.

**Comment by jmaunon** [comment]
Thanks a lot for your issue!
I do not know if I have understood you as well. If you use docker-compose in a single laptop, in this laptop you will have all the services running and they are capable of communication between them. 

If you go to another laptop and do the same procedure, you will have (again) the same services in this other laptop, but notice that both laptops will never communicate between them, you should address the real url.

**Comment by b02202050** [comment]
Yeah, Thanks @jmaunon ,
As you say, but how to configure the url in the docker compose file of one computer and how to set `grid address` on another computer to communicate (In the case of two IPs: 192.168.51.177 and 192.168.51.189)?

**Comment by IonesioJunior** [comment]
Hello @b02202050, did you find a solution for your doubt/issue?

**Comment by madhavajay** [comment]
`0.2.x` is no longer supported. Please refer to the new `0.5` release.
