### ISSUE TITLE
how to fix FL Process already exists error?

### ISSUE THREAD

**Issue by zzaebok** [OpenMined/PyGrid#758]
## Question
how to fix FL Process already exists error?

## Further Information
I tried to run '01-Create-plan.ipynb' in examples/model-centric.
When I first ran it, it ran well.
In order to run demo-app in KotlinSyft, I restarted the notebook again.
But I found that hosting failed due to FL process already exists error (screenshot below)
Even after rebooting my computer, it produces the same error message.
How can I kill the previous host? or How can I fix it?

I just followed instructions exactly like here.
https://github.com/OpenMined/KotlinSyft#running-the-demo-app
And I found that error in this step 'Run the notebook 01-Create-plan.ipynb. It should host the model on PyGrid.'

Thank you

### Edit (2020.12.03)
I found that FL process is alive even though I reboot my computer.
I could restart another process by change its name or version.
But, I still don't know how to turn it off.
How can I shut the PyGrid host??

## Screenshots
![Screenshot from 2020-12-02 15-10-03](https://user-images.githubusercontent.com/44357534/100835418-f2f59000-34b0-11eb-9262-b51d5dee9600.png)

## System Information
 - OS: Ubuntu
 - OS Version: 18.04
 - Language Version: Python 3.7
 - Package Manager Version: Conda 4.8.3

**Comment by vnitu02** [comment]
I solved this issue by cleaning the docker cache:
`docker system prune -a`

**Comment by bibs2091** [comment]
I have the same problem,
`docker system prune -a
`
didn't solve it

**Comment by vnitu02** [comment]
Try to change the `version` in both _Create-plan_ and _ExecutePlan_

**Comment by zzaebok** [comment]
> Try to change the `version` in both _Create-plan_ and _ExecutePlan_

Thanks for the reply. I found that if I change the version or name solve the problem.
But I think the simple change of version or name isn't a real answer :cry:

**Comment by shujaat81** [comment]
> > Try to change the `version` in both _Create-plan_ and _ExecutePlan_
> 
> Thanks for the reply. I found that if I change the version or name solve the problem.
> But I think the simple change of version or name isn't a real answer 😢

You don't have to change the version, restart the node from grid (where the model has been hosted).
This is because the model with the version is already there being hosted.

**Comment by IMVector** [comment]
> > Try to change the `version` in both _Create-plan_ and _ExecutePlan_
> 
> Thanks for the reply. I found that if I change the version or name solve the problem.
> But I think the simple change of version or name isn't a real answer 😢

Have you solved it?  How to fix it without changing the version?
