### ISSUE TITLE
running 'docker-compose up' and not having to rebuild every time a change made in code 

### ISSUE THREAD

**Issue by bibs2091** [OpenMined/PyGrid#762]
## Description
if you run the command `docker-compose up` and play around in the Jupiter notebook then you change a part in the 'node' code source per example, you'll need to rebuild the container again, which can be a pain in development phase, the improvement is the ability to change the behavior based on the new change in the code without having to rebuild again.
 
## Are you interested in working on this improvement yourself?
- Yes, I am, in fact I tried adding volumes to the each on of the services and I couldn't see a difference, here's a snippet of the change in the 'docker-compose.yml' file (i did pretty much the same for all services except for the Jupiter one but I included here only two):
![image](https://user-images.githubusercontent.com/28659618/102279941-85277a80-3f2c-11eb-8ec4-4c09576e991b.png)
![image](https://user-images.githubusercontent.com/28659618/102279959-8f497900-3f2c-11eb-8cae-b3e4192951ca.png)
if you detected an error please feel to comment and tell me how to fix it.

**Comment by madhavajay** [comment]
`0.2.x` is no longer supported. Please refer to the new `0.5` release.
