### ISSUE TITLE
Trying to run new jupyter notebook on different node: 8899 

### ISSUE THREAD

**Issue by shujaat81** [OpenMined/PyGrid#765]
I have created new network, able to run new node and network after editing the docker-compose.yml file. Image and network has been created as per instruction, but getting the error:   

"jupyter2_1      | Error: '' is not a valid port number.
jupyter2_1      |
pygrid_jupyter2_1 exited with code 1"

yml file::

version: '3'
services:
  network:
    image: openmined/grid-network:production
    build: ./apps/network
    environment:
      - PORT=7000
      - SECRET_KEY=ineedtoputasecrethere
      - DATABASE_URL=sqlite:///databasenetwork.db
    ports:
      - 7000:7000
  
  charlie:
    image: openmined/grid-node:production
    build: ./apps/node
    environment:
      - NODE_ID=Charlie
      - ADDRESS=http://charlie:7001/
      - PORT=7001
      - NETWORK=http://network:7000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'network'
    ports:
      - 7001:7001
  dan:
    image: openmined/grid-node:production
    build: ./apps/node
    environment:
      - NODE_ID=Dan
      - ADDRESS=http://dan:7002/
      - PORT=7002
      - NETWORK=http://network:7000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'network'
    ports:
      - 7002:7002

  jupyter:
    image: openmined/pysyft-notebook:3852ca9e78d5163b52776b231f469e32e6c8be01  # syft 0.2.9
    depends_on:
      - 'dan'
    ports:
      - 8888:8888
    volumes:
    - ./examples:/workspace/examples

  modelnetwork:
    image: openmined/grid-network2:production2
    build: ./apps/network
    environment:
      - PORT=8000
      - SECRET_KEY=ineedtoputasecretherealso
      - DATABASE_URL=sqlite:///databasenetwork.db
    ports:
      - 8000:8000
  
  ahkam:
    image: openmined/grid-node:production
    build: ./apps/node
    environment:
      - NODE_ID=Ahkam
      - ADDRESS=http://ahkam:8001/
      - PORT=8001
      - NETWORK=http://modelnetwork:8000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'modelnetwork'
    ports:
      - 8001:8001

  jupyter2:
    image: openmined/pysyft-notebook:3852ca9e78d5163b52776b231f469e32e6c8be02  # syft 0.2.9
    depends_on:
      - 'modelnetwork'
    ports:
      - 8899:8899
    volumes:
    - ./examples2:/workspace/examples2

**Comment by IonesioJunior** [comment]
Hello @shujaat81 did you find a solution for your issue? Is there anything that I can do to help you?

**Comment by madhavajay** [comment]
`0.2.x` is no longer supported. Please refer to the new `0.5` release.
