### ISSUE TITLE
ModuleNotFoundError: No module named 'syft.serde'

### ISSUE THREAD

**Issue by vinayentc** [OpenMined/PyGrid#770]
## Description
On Executing - examples/model-centric/01-Create-plan.ipynb# receive the below error -

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-258ba5c269f5> in <module>
      3 
      4 import syft as sy
----> 5 from syft.serde import protobuf
      6 from syft_proto.execution.v1.plan_pb2 import Plan as PlanPB
      7 from syft_proto.execution.v1.state_pb2 import State as StatePB

ModuleNotFoundError: No module named 'syft.serde'

## System Information
 - OS: MacOS

## Additional Context
Followed the mentioned steps, however none of the package can be imported.

**Comment by longquangpham90** [comment]
me to can not import moduel

**Comment by madhavajay** [comment]
`0.2.x` is no longer supported. Please refer to the new `0.5` release.
