### ISSUE TITLE
load_pem_private_key() missing 1 required positional argument: 'backend'

### ISSUE THREAD

**Issue by koloskova** [OpenMined/PyGrid#771]
When I try to run the model-centric example https://github.com/OpenMined/PyGrid/blob/dev/examples/model-centric/01-Create-plan.ipynb, on step 4 (check hosted data) I get the following error: 

![image](https://user-images.githubusercontent.com/19473236/107100125-bda05200-6813-11eb-97f1-11b97cc56e5f.png)

**Comment by jmaunon** [comment]
Thanks for your feedback @koloskova .
Could provide more detail about versions?

I have checked that examples run without problems (at least from last commit on `dev`)

https://github.com/OpenMined/PyGrid/runs/1584871170?check_suite_focus=true

These examples will be deprecated once 'pysyft >= 0.3.0`are integrated

**Comment by koloskova** [comment]
Thanks for your reply. I have installed pyjwt-2.0.1

**Comment by koloskova** [comment]
If it helps, pip list gives me:
Package                Version            
---------------------- -------------------
absl-py                0.10.0             
aioice                 0.6.18             
aiortc                 0.9.28             
asn1crypto             1.3.0              
astor                  0.8.1              
attrs                  20.1.0             
av                     8.0.2              
backcall               0.2.0              
bleach                 3.1.5              
certifi                2020.6.20          
cffi                   1.14.0             
chardet                3.0.4              
click                  7.1.2              
conda                  4.8.4              
conda-package-handling 1.6.0              
crc32c                 2.1                
cryptography           2.8                
decorator              4.4.2              
defusedxml             0.6.0              
dill                   0.3.2              
entrypoints            0.3                
Flask                  1.1.2              
Flask-SocketIO         4.2.1              
gast                   0.2.2              
google-pasta           0.2.0              
grpcio                 1.32.0             
h5py                   2.10.0             
idna                   2.8                
importlib-metadata     1.7.0              
importlib-resources    1.5.0              
ipykernel              5.3.4              
ipython                7.18.1             
ipython-genutils       0.2.0              
ipywidgets             7.5.1              
itsdangerous           1.1.0              
jedi                   0.17.2             
Jinja2                 2.11.2             
joblib                 0.16.0             
jsonschema             3.2.0              
jupyter                1.0.0              
jupyter-client         6.1.6              
jupyter-console        6.2.0              
jupyter-core           4.6.3              
Keras-Applications     1.0.8              
Keras-Preprocessing    1.1.2              
lz4                    3.0.2              
Markdown               3.2.2              
MarkupSafe             1.1.1              
mistune                0.8.4              
msgpack                1.0.0              
nbconvert              5.6.1              
nbformat               5.0.7              
netifaces              0.10.9             
notebook               5.7.8              
numpy                  1.18.5             
openmined.threepio     0.2.0              
opt-einsum             3.3.0              
packaging              20.4               
pandocfilters          1.4.2              
parso                  0.7.0              
pexpect                4.8.0              
phe                    1.4.0              
pickleshare            0.7.5              
Pillow                 7.2.0              
pip                    20.0.2             
prometheus-client      0.8.0              
prompt-toolkit         3.0.7              
protobuf               3.13.0             
psutil                 5.7.0              
ptyprocess             0.6.0              
pycosat                0.6.3              
pycparser              2.19               
pyee                   7.0.3              
Pygments               2.6.1              
PyJWT                  2.0.1              
pylibsrtp              0.6.6              
pyOpenSSL              19.1.0             
pyparsing              2.4.7              
pyrsistent             0.16.0             
PySocks                1.7.1              
python-dateutil        2.8.1              
python-engineio        3.13.2             
python-socketio        4.6.0              
PyYAML                 5.3.1              
pyzmq                  19.0.1             
qtconsole              4.7.6              
QtPy                   1.9.0              
requests               2.22.0             
requests-toolbelt      0.9.1              
RestrictedPython       5.0                
ruamel-yaml            0.15.87            
scikit-learn           0.23.2             
scipy                  1.4.1              
Send2Trash             1.5.0              
setuptools             45.2.0.post20200210
shaloop                0.2.1a11           
six                    1.14.0             
syft                   0.2.9              
syft-proto             0.5.2              
tblib                  1.6.0              
tensorboard            1.15.0             
tensorflow             1.15.3             
tensorflow-estimator   1.15.1             
termcolor              1.1.0              
terminado              0.8.3              
testpath               0.4.4              
tf-encrypted           0.5.9              
threadpoolctl          2.1.0              
torch                  1.4.0              
torchvision            0.5.0              
tornado                4.5.3              
tqdm                   4.42.1             
traitlets              4.3.3              
urllib3                1.25.8             
wcwidth                0.2.5              
webencodings           0.5.1              
websocket-client       0.57.0             
websockets             8.1                
Werkzeug               1.0.1              
wheel                  0.34.2             
widgetsnbextension     3.5.1              
wrapt                  1.12.1             
zipp                   3.1.0              
Note: you may need to restart the kernel to use updated packages.

**Comment by koloskova** [comment]
I solved this issue by modifying the cell to 
!pip install 'pyjwt==1.7.1'
