### ISSUE TITLE
[Vanity API] Association Request Routes

### ISSUE THREAD

**Issue by IonesioJunior** [OpenMined/PyGrid#772]
## Description
Create vanity API routes for Domain Node Initial Association Request Feature

Send Association Request
Request: POST /association-requests/request
Body: name, address
Description: Creates a new association request in the database and then sends this request to the address in the body at the “receive association request” endpoint described below. This endpoint will also store and send a handshake value which is a randomly generated hash that serves as a unique identifier of the request. Only users with the permission of can_manage_infrastructure can create an association request.

Receive Association Request
Request: POST /association-requests/receive
Body: address, handshake, value
Description: This endpoint looks up whether or not the request’s handshake value already exists in the database. If the handshake value does not exist, a new association request will be created. If the handshake value does exist, the system will assume that the association request is a response to an existing request and receive a value of either “accept” or “deny”. This will indicate that the request for a given handshake was either accepted or denied.

Note: As a form of security, this endpoint will need to view the HTTP request to ensure that the party sending the request was indeed the same as the address. If not, then this is a fake request and should be ignored.
Respond to Association Request
Request: POST /association-requests/respond
Body: address, handshake, value
Description: Creates a new response to an existing association request. This will fire off an API call to the address in the body at the “receive association request” endpoint described above. It will pass with it a value of either “accept” or “deny” indicating whether the request should be marked as accepted or denied. Only users with the permission of can_manage_infrastructure can respond to an association request.

Get Association Request
Request: GET /association-requests/{id}
Body: N/A
Description: Gets an individual association request. Only users with the permission of can_manage_infrastructure can get an association request.

Get Association Requests
Request: GET /association-requests
Body: N/A
Description: Gets all association requests. Only users with the permission of can_manage_infrastructure can get all association requests.

Delete Association Request
Request: DELETE /association-requests/{id}
Body: N/A
Description: Deletes an association request. Only users with the permission of can_manage_infrastructure can delete an association request.

## Additional Context
- [PyGrid Roadmap](https://docs.google.com/document/d/1_aFR69cTw3BnSLk0jYOd-vXMhNrZkbuEezST-mM2q1k/edit#heading=h.s0sl8c8kxwy3)

**Comment by DayvsonNascimento** [comment]
Hello, I would like to work on this issue. Could you please assign this issue for me?

**Comment by IonesioJunior** [comment]
It's yours!

**Comment by IonesioJunior** [comment]
Closed by #782
