### ISSUE TITLE
[Vanity API] Role Routes

### ISSUE THREAD

**Issue by IonesioJunior** [OpenMined/PyGrid#773]
## Description
Create vanity API routes for Domain Node Initial Role Feature

Create Role
Request: POST /roles
Body: name, can_edit_settings, can_create_users, can_edit_roles, can_manage_infrastructure
Description: Creates a new role. Only users with the permission of can_edit_roles can create a role.

Get Role
Request: GET /roles/{id}
Body: N/A
Description: Gets an individual role. Only users with the permission of can_edit_settings can get a role.

Get Roles
Request: GET /roles
Body: N/A
Description: Gets all roles. Only users with the permission of can_edit_settings can get all roles.

Update Role
Request: PUT /roles/{id}
Body: name, can_edit_settings, can_create_users, can_edit_roles, can_manage_infrastructure
Description: Updates a role. Only users with the permission of can_edit_roles can edit a role.

Delete Role
Request: DELETE /roles/{id}
Body: N/A
Description: Deletes a role. Only users with the permission of can_edit_roles can delete a role.

## Additional Context
- [PyGrid Roadmap](https://docs.google.com/document/d/1_aFR69cTw3BnSLk0jYOd-vXMhNrZkbuEezST-mM2q1k/edit#heading=h.s0sl8c8kxwy3)

**Comment by yovanycunha** [comment]
I would like to work on this

**Comment by IonesioJunior** [comment]
It's yours!
