### ISSUE TITLE
Can you please specify which version of PySyft I should used to launch examples?

### ISSUE THREAD

**Issue by burlachenkok** [OpenMined/PyGrid#776]
It seems there are a lot of API backward incompatible changes has been made during moving from 0.2.* into 0.3.0

The examples are not launchable in the last version of PySyft, which in particular exclude TorchHook

**Comment by jmaunon** [comment]
Hi @burlachenkok . In the `README` file there is a statement indicating that `pygrid` only supports `pysyft 0.2.x`. Hopefully `pysyft 0.3.0` will be integrated soon.

**Comment by burlachenkok** [comment]
Thanks. Please share if there are any timelines or so on that?
Because pysyft 0.3.* did a lot of backward-incompatible changes compare to 0.2.*

**Comment by madhavajay** [comment]
Currently `pygrid_0.4.0` matches PySyft `dev` (roughly Syft 0.4+) we are working to bring both together very shortly and then make a release.

**Comment by madhavajay** [comment]
Moving forward we will try to keep both PyGrid and PySyft at version parity, our official `0.5` release is coming any day now.
