### ISSUE TITLE
Cant run Data Centric Examples - "Too many values to unpack" when searching grid

### ISSUE THREAD

**Issue by zularian** [OpenMined/PyGrid#780]
## Description
Hello all,

I have set up a network on my computers via Docker (Tag: production). I use PySyft 0.2.8 so it is compatible with PyGrid. One computer is the network and another is the node. I ran the Introduction example and the Data Owner part works fine. But in the Data Scientist part, the grid cannot be searched and I get following error:

![grafik](https://user-images.githubusercontent.com/79311879/108498413-1d373c80-72ad-11eb-8458-7bfe71ddf9c6.png)

I have checked if the dataset is in it as follows:
`print("Node tags: ", requests.get(node_address + "/data-centric/dataset-tags").json())`

I also checked if the Network has his node via http-Request: 192.168.8.105:7000/connected-nodes

When I manually search in Postman, I get following message:

![grafik](https://user-images.githubusercontent.com/79311879/108499604-d9453700-72ae-11eb-8786-0ba45e424a40.png)

I also looked up to the definition of search in public_grid.py and added a print of the match_nodes, which results in `{'message': 'Invalid JSON format.'}`:

```

def search(self, *query: Union[str]) -> Dict[Any, Any]:
        """ Search a set of tags across the grid network.

        Args:
            query : A set of dataset tags.
        Returns:
            tensor_results : matrix of tensor pointers.
        """
        # Ask gateway about desired tags
        body = json.dumps({"query": list(query)})
        match_nodes = self._ask_gateway(requests.post, GATEWAY_ENDPOINTS.SEARCH_TAGS, body)
        print(match_nodes) #added this line
        # Connect with grid nodes that contains the dataset and get their pointers
        tensor_results = {}
        for node_id, node_url in match_nodes:
            worker = self.__connect_with_node(node_id, node_url)
            tensor_results[node_id] = worker.search(query)
        return tensor_results
```

Here is my code for the Data Scientist part:

```
from syft.grid.public_grid import PublicGridNetwork
import torch as th
import syft as sy
import requests

hook = sy.TorchHook(th)

grid_address = "http://192.168.8.105:7000"
node_address = "http://192.168.8.132:5000"
grid = PublicGridNetwork(hook, grid_address)

print("Node tags: ", requests.get(node_address + "/data-centric/dataset-tags").json())

results = grid.search("#February", "#birth-records")
results
```

I also tried the MNIST-Example but I get the same error message as above. The same error appeared in an older issue #747 but it wasn't solved yet.

## How to Reproduce
1. Execute the introduction example of data centric (https://github.com/OpenMined/PyGrid/blob/dev/examples/data-centric/introduction/01-introduction-to-pygrid.ipynb)
2. Execute the mnist example (https://github.com/OpenMined/PyGrid/tree/dev/examples/data-centric/mnist)

## Expected Behavior
Return the results of the grid search.

## System Information
 - OS: Windows
 - OS Version: 10
 - Language Version: Python 3.7, PySyft 0.2.8

Thanks in advance!

**Comment by jmaunon** [comment]
Updagre to pysyft 0.2.x

**Comment by zularian** [comment]
I managed to get the examples to work. First I took the Docker with the tag development instead of production. Also, I tested a different state of PyGrid (https://github.com/OpenMined/PyGrid/commit/0a837a14d000f29e1cd732f2fcdd3e901639c06f), with this one it works fine.

**Comment by madhavajay** [comment]
`0.2.x` is no longer supported. Please refer to the new `0.5` release.
